import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {_electron as electron} from 'playwright';
const require=createRequire(import.meta.url),electronPath=require('electron'),project=path.resolve('.');
const launch=dataDir=>electron.launch({executablePath:process.env.JERRI_ELECTRON_EXECUTABLE||electronPath,args:process.env.JERRI_PACKAGED==='1'?[]:[path.join(project,'electron','main.mjs')],env:{...process.env,JERRI_DATA_DIR:dataDir}});
const axeSource=fs.readFileSync(require.resolve('axe-core/axe.min.js'),'utf8');
const assertAccessible=async(page,state)=>{const cdp=await page.context().newCDPSession(page);await cdp.send('Runtime.evaluate',{expression:axeSource,allowUnsafeEvalBlockedByCSP:true});const result=await page.evaluate(()=>globalThis.axe.run(document));assert.deepEqual(result.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)})),[],`${state} accessibility violations`)};

test('automated WCAG scan of every permanent screen and transaction dialog', {timeout:120000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-a11y-'));let app;try{app=await launch(path.join(root,'data'));const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await assertAccessible(page,'empty Dashboard');await page.getByRole('button',{name:'Transactions',exact:true}).click();await assertAccessible(page,'Transactions');await page.getByRole('button',{name:'Add manually'}).click();await page.getByRole('dialog').waitFor();await assertAccessible(page,'Transaction dialog');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Settings',exact:true}).click();await assertAccessible(page,'Settings');const fixtureRoot=path.join(project,'test-fixtures','synthetic','2026-08'),paths=[path.join(fixtureRoot,'Stripe_Itemised_Payouts_2026-08.csv'),path.join(fixtureRoot,'Xero_Payslip_2026-08.pdf'),path.join(fixtureRoot,'ING_Orange_Everyday_2026-08.pdf')];await app.evaluate(({dialog},selected)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:selected})},paths);await page.getByRole('button',{name:'Add files',exact:true}).click();await page.getByRole('dialog').waitFor();await assertAccessible(page,'Import preview dialog');await page.getByRole('dialog').focus();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'detached'});await page.getByRole('button',{name:'Add files',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Confirm import'}).click();await page.locator('.summary-grid').waitFor();await assertAccessible(page,'Populated Dashboard');await page.locator('.attention').click();await page.locator('.bulk-review').waitFor();await assertAccessible(page,'Bulk review list');await page.getByRole('button',{name:'Select all'}).click();await assertAccessible(page,'Selected bulk review list')}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});
