import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {FinanceStore} from '../electron/store.mjs';

const synthetic=path.resolve('test-fixtures/synthetic/2026-08');
const stripe=path.join(synthetic,'Stripe_Itemised_Payouts_2026-08.csv');
const xero=path.join(synthetic,'Xero_Payslip_2026-08.pdf');
const bank=path.join(synthetic,'ING_Orange_Everyday_2026-08.pdf');
const fixture=(overrides={})=>({date:'2026-08-10',description:'Adversarial item',amountCents:10000,kind:'income',scope:'business_affiliate',category:'Affiliate Marketing Income',reviewStatus:'confirmed',profitIncluded:true,note:'',...overrides});
const withStore=async fn=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-adversarial-')),store=new FinanceStore(path.join(dir,'live.sqlite'));try{return await fn(store,dir)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}};

test('selecting the same file twice is handled as one ready file, not a failed confirmation',()=>withStore(async store=>{const preview=await store.preview([stripe,stripe]);assert.equal(preview.files.length,2);assert.equal(preview.files.filter(file=>file.duplicate).length,1);assert.equal(preview.transactionCount,8);store.confirm(preview);assert.equal(store.transactions({month:'2026-08'}).length,8);assert.equal(store.imports().filter(item=>!item.revertedAt).length,1)}));

test('stale preview confirmation is idempotent when the user double-submits',()=>withStore(async store=>{const preview=await store.preview([stripe]);store.confirm(preview);store.confirm(preview);assert.equal(store.transactions({month:'2026-08'}).length,8);assert.equal(store.imports().length,1)}));

test('a duplicate payslip cannot falsely match a newly selected bank deposit',()=>withStore(async store=>{store.confirm(await store.preview([xero]));const preview=await store.preview([xero,bank]);assert.equal(preview.files.find(file=>file.source==='xero').duplicate,true);assert.equal(preview.matchedEmployment,0);const payroll=preview.files.find(file=>file.source==='ing').transactions.find(tx=>/PAYROLL/.test(tx.description));assert.equal(payroll.kind,'unknown');assert.equal(payroll.reviewStatus,'needs_review');assert.equal(preview.needsReview,10)}));

test('remembered merchant rules do not override authoritative payroll matching',()=>withStore(async store=>{store.db.prepare('INSERT INTO rules VALUES(?,?,?,?,?,?,?)').run('rule','HEALTH CO PAYROLL','expense','business_pt','Software',1,new Date().toISOString());const preview=await store.preview([xero,bank]);const payroll=preview.files.find(file=>file.source==='ing').transactions.find(tx=>/PAYROLL/.test(tx.description));assert.equal(preview.matchedEmployment,1);assert.equal(payroll.kind,'transfer');assert.equal(payroll.reviewStatus,'confirmed');assert.equal(payroll.profitIncluded,false)}));

test('manual create and update enforce dates, enums, signs, non-zero cents, and confirmed profit',()=>withStore(store=>{const invalid=[fixture({date:'2026-02-30'}),fixture({amountCents:0}),fixture({amountCents:1.2}),fixture({amountCents:-100,kind:'income'}),fixture({amountCents:100,kind:'expense'}),fixture({kind:'bogus'}),fixture({scope:'bogus'}),fixture({reviewStatus:'bogus'}),fixture({category:''}),fixture({reviewStatus:'needs_review',profitIncluded:true})];for(const input of invalid)assert.throws(()=>store.createTransaction(input));assert.equal(store.transactions({}).length,0);const valid=store.createTransaction(fixture());assert.throws(()=>store.updateTransaction({...valid,date:'not-a-date'}));assert.equal(store.transactions({})[0].date,'2026-08-10')}));

test('bulk review is atomic, validates every selection, and records one audit event',()=>withStore(store=>{const awaiting={kind:'unknown',scope:'unknown',category:'Needs Review',reviewStatus:'needs_review',profitIncluded:false},first=store.createTransaction(fixture({...awaiting,description:'Bulk review first'})),second=store.createTransaction(fixture({...awaiting,date:'2026-08-11',description:'Bulk review second'})),confirmed=store.createTransaction(fixture({date:'2026-08-12',description:'Already confirmed'}));assert.throws(()=>store.reviewTransactions([first.id,confirmed.id]),/Only transactions awaiting review/);assert.equal(store.transactions({reviewStatus:'needs_review'}).length,2);assert.throws(()=>store.reviewTransactions([first.id,first.id]),/invalid/);const result=store.reviewTransactions([first.id,second.id]);assert.deepEqual(result,{count:2});assert.equal(store.transactions({reviewStatus:'needs_review'}).length,0);const audit=store.db.prepare("SELECT details_json FROM audit WHERE action='bulk_review_transactions'").get();assert.deepEqual(JSON.parse(audit.details_json),{count:2,transactionIds:[first.id,second.id]})}));
test('dashboard all-time mode aggregates every month and preserves the monthly trend',()=>withStore(store=>{for(const [date,amount] of [['2026-08-01',10000],['2026-09-01',20000],['2026-10-01',-5000]])store.createTransaction(fixture({date,description:`All time ${date}`,amountCents:amount,kind:amount>0?'income':'expense',category:amount>0?'Affiliate Marketing Income':'Software'}));const all=store.dashboard('all');assert.equal(all.mode,'all');assert.equal(all.transactionCount,3);assert.equal(all.summary.cashIn,30000);assert.equal(all.summary.cashOut,5000);assert.equal(all.summary.cashRemaining,25000);assert.deepEqual(all.trend.map(row=>row.month),['2026-08','2026-09','2026-10'])}));

test('allocation backend rejects negative, over-100, missing, NaN, and invalid effective months',()=>withStore(store=>{const base={effectiveMonth:'2026-09',ownersPay:30,tax:25,savings:10,investments:10,education:5,travel:5,creditCardDebt:15};for(const allocation of [{...base,effectiveMonth:''},{...base,ownersPay:-1,tax:56},{...base,ownersPay:101,tax:-46},{...base,savings:undefined,tax:35},{...base,travel:NaN,tax:30}])assert.throws(()=>store.saveSettings({allocation}));assert.equal(store.allocationFor('2026-09').ownersPay,30)}));

test('snapshot validation, exact-month loading, and snapshot-only month navigation are safe',()=>withStore(store=>{const valid={month:'2027-01',savingsCents:10000,investmentsCents:0,superCents:0,otherAssetsCents:0,creditCardCents:0,loansCents:0,otherLiabilitiesCents:0,note:'future'};for(const bad of [{...valid,month:'2027-13'},{...valid,savingsCents:-1},{...valid,savingsCents:1.5},{...valid,savingsCents:Infinity}])assert.throws(()=>store.saveSnapshot(bad));store.saveSnapshot(valid);assert.equal(store.snapshotFor('2027-01').savingsCents,10000);assert.equal(store.snapshotFor('2027-02').savingsCents,0);assert.deepEqual(store.bootstrap().months,['2027-01']);assert.equal(store.bootstrap().dashboard.month,'2027-01');assert.equal(store.bootstrap().dashboard.financial.netWorthCents,10000)}));

test('ledger does not silently truncate after one thousand records',()=>withStore(store=>{for(let i=0;i<1005;i++)store.createTransaction(fixture({date:`2026-08-${String(i%28+1).padStart(2,'0')}`,description:`Bulk ${i}`,amountCents:i+1,profitIncluded:false}));assert.equal(store.transactions({month:'2026-08'}).length,1005);assert.equal(store.dashboard('2026-08').transactionCount,1005)}));

test('search treats percent and underscore as literal text rather than wildcard operators',()=>withStore(store=>{store.createTransaction(fixture({description:'Fee 100% complete',profitIncluded:false}));store.createTransaction(fixture({description:'plain item',date:'2026-08-11',profitIncluded:false}));assert.equal(store.transactions({search:'%'}).length,1);assert.equal(store.transactions({search:'_'}).length,0);assert.equal(store.transactions({search:'100%'}).length,1)}));

test('Stripe parser rejects invalid money, currency, status, date, reconciliation, and repeated identity',()=>withStore(async(store,dir)=>{const original=fs.readFileSync(stripe,'utf8');const variants=[['money',s=>s.replace(',120.00,0.00,120.00,',',oops,0.00,120.00,')],['currency',s=>s.replace(',aud,',',usd,')],['status',s=>s.replace(/,paid\r?\n/,',pending\n')],['date',s=>s.replace('2026-08-03 09:00:00','2026-02-30 09:00:00')],['reconcile',s=>s.replace(',120.00,0.00,120.00,',',120.00,1.00,120.00,')]];for(const [name,mutate] of variants){const file=path.join(dir,`${name}.csv`);fs.writeFileSync(file,mutate(original));await assert.rejects(()=>store.preview([file]),/Stripe row 2 is invalid/)}const lines=original.trim().split(/\r?\n/),duplicate=path.join(dir,'duplicate.csv');fs.writeFileSync(duplicate,[lines[0],lines[1],lines[1]].join('\n'));await assert.rejects(()=>store.preview([duplicate]),/Duplicate transaction identity/)}));

test('backup and restore reject the live path and structurally unrelated SQLite without closing live state',()=>withStore((store,dir)=>{store.createTransaction(fixture());assert.throws(()=>store.backup(store.dbPath),/different/);assert.throws(()=>store.restore(store.dbPath),/different/);const unrelated=path.join(dir,'unrelated.sqlite'),db=new DatabaseSync(unrelated);db.exec('CREATE TABLE transactions(id TEXT)');db.close();assert.throws(()=>store.restore(unrelated),/valid Jerri Finance backup/);assert.equal(store.transactions({}).length,1);store.createTransaction(fixture({date:'2026-08-11',description:'Still usable'}));assert.equal(store.transactions({}).length,2)}));

test('successful backup includes rules, settings, snapshots, imports, transactions, and audit state',()=>withStore(async(store,dir)=>{store.confirm(await store.preview([stripe]));const reviewed=store.createTransaction(fixture({kind:'unknown',scope:'unknown',category:'Needs Review',reviewStatus:'needs_review',profitIncluded:false}));store.updateTransaction({...reviewed,kind:'income',scope:'business_affiliate',category:'Affiliate Marketing Income',reviewStatus:'confirmed',profitIncluded:true,rememberRule:true});store.saveSettings({allocation:{effectiveMonth:'2026-09',ownersPay:25,tax:25,savings:15,investments:10,education:5,travel:5,creditCardDebt:15}});store.saveSnapshot({month:'2026-09',savingsCents:12300,investmentsCents:0,superCents:0,otherAssetsCents:0,creditCardCents:0,loansCents:0,otherLiabilitiesCents:0,note:'backup'});const before=Object.fromEntries(['imports','transactions','rules','allocation_profiles','snapshots','audit'].map(table=>[table,store.db.prepare(`SELECT COUNT(*) count FROM ${table}`).get().count])),backup=path.join(dir,'backup.sqlite');store.backup(backup);store.deleteTransaction(reviewed.id);store.restore(backup);const after=Object.fromEntries(Object.keys(before).map(table=>[table,store.db.prepare(`SELECT COUNT(*) count FROM ${table}`).get().count]));assert.deepEqual(after,before);assert.equal(store.snapshotFor('2026-09').savingsCents,12300);assert.equal(store.allocationFor('2026-09').ownersPay,25)}));

test('Stripe money grammar rejects sub-cent, exponent, and malformed comma values',()=>withStore(async(store,dir)=>{const original=fs.readFileSync(stripe,'utf8'),variants=[['sub-cent',s=>s.replace(',120.00,0.00,120.00,',',120.001,0.00,120.001,')],['exponent',s=>s.replace(',120.00,0.00,120.00,',',1.2e2,0.00,1.2e2,')],['commas',s=>s.replace(',120.00,0.00,120.00,',',"1,2,0.00",0.00,120.00,')]];for(const [name,mutate] of variants){const file=path.join(dir,`${name}.csv`);fs.writeFileSync(file,mutate(original));await assert.rejects(()=>store.preview([file]),/Stripe row 2 is invalid/)}}));

test('invalid allocation rolls back every scalar setting atomically',()=>withStore(store=>{const invalid={effectiveMonth:'2026-09',ownersPay:30,tax:25,savings:10,investments:10,education:5,travel:5,creditCardDebt:14};assert.throws(()=>store.saveSettings({currency:'AUD',setupComplete:true,financialYearStartMonth:8,allocation:invalid}),/exactly 100/);const settings=store.settings();assert.equal(settings.currency,'AUD');assert.equal(settings.setupComplete,false);assert.equal(settings.financialYearStartMonth,7);assert.throws(()=>store.saveSettings({currency:'NZD'}),/AUD only/);assert.throws(()=>store.saveSettings({financialYearStartMonth:13}),/1 to 12/)}));

test('undo removes dangling cross-file match metadata and reopens unmatched payroll for review',()=>withStore(async store=>{store.confirm(await store.preview([stripe,xero,bank]));const xeroImport=store.imports().find(item=>item.source==='xero');store.undoImport(xeroImport.id);const payroll=store.transactions({month:'2026-08'}).find(tx=>/PAYROLL/.test(tx.description));assert.equal(payroll.kind,'unknown');assert.equal(payroll.scope,'unknown');assert.equal(payroll.reviewStatus,'needs_review');assert.equal(payroll.profitIncluded,false);assert.equal(payroll.metadata.matchedXeroKey,undefined);const activeKeys=new Set(store.transactions({}).map(tx=>tx.sourceKey));for(const tx of store.transactions({}))for(const key of ['matchedXeroKey','matchedStripeKey','matchedBankKey'])if(tx.metadata[key])assert.equal(activeKeys.has(tx.metadata[key]),true)}));

test('backup validation rejects incomplete schemas and corrupt semantic rows before replacing live data',()=>withStore((store,dir)=>{const original=store.createTransaction(fixture()),incomplete=path.join(dir,'incomplete.sqlite'),semantic=path.join(dir,'semantic.sqlite');store.backup(incomplete);fs.copyFileSync(incomplete,semantic);let db=new DatabaseSync(incomplete);db.exec('ALTER TABLE imports DROP COLUMN summary');db.close();db=new DatabaseSync(semantic);db.prepare('UPDATE transactions SET metadata_json=? WHERE id=?').run('not-json',original.id);db.close();assert.throws(()=>store.restore(incomplete),/valid Jerri Finance backup/);assert.throws(()=>store.restore(semantic),/valid Jerri Finance backup/);assert.equal(store.transactions({})[0].id,original.id);store.createTransaction(fixture({date:'2026-08-11',description:'Still writable after rejected restore'}));assert.equal(store.transactions({}).length,2);assert.equal(fs.existsSync(store.dbPath+'.restore-backup'),false)}));

test('failed backup replacement restores the previous known-good backup',()=>withStore((store,dir)=>{store.createTransaction(fixture());const target=path.join(dir,'backup.sqlite');store.backup(target);store.createTransaction(fixture({date:'2026-08-11',description:'After first backup'}));const rename=fs.renameSync;try{fs.renameSync=(source,destination)=>{if(String(source).includes('.tmp-')&&destination===target)throw new Error('injected rename failure');return rename(source,destination)};assert.throws(()=>store.backup(target),/injected rename failure/)}finally{fs.renameSync=rename}const restored=new FinanceStore(path.join(dir,'restored.sqlite'));try{restored.restore(target);assert.equal(restored.transactions({}).length,1)}finally{restored.close()}}));

test('backup validation rejects dangling non-reciprocal match metadata',()=>withStore((store,dir)=>{const transaction=store.createTransaction(fixture()),backup=path.join(dir,'dangling.sqlite');store.backup(backup);const db=new DatabaseSync(backup);db.prepare('UPDATE transactions SET metadata_json=? WHERE id=?').run(JSON.stringify({manual:true,matchedBankKey:'ing:missing'}),transaction.id);db.close();assert.throws(()=>store.restore(backup),/valid Jerri Finance backup/);assert.equal(store.transactions({})[0].id,transaction.id)}));
