import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {previewPaths} from '../electron/importers.mjs';import {FinanceStore} from '../electron/store.mjs';
const fixtures=path.resolve('customer-inputs');const stripe=path.join(fixtures,'Itemised_payouts_AUD_2026-07-01_to_2026-07-31_Australia-Melbourne.csv');const payslip=path.join(fixtures,'PaySlip (7).pdf');const bank=path.join(fixtures,'Expenses Statement.pdf');
test('real Stripe fixture reconciles exactly',async()=>{const p=await previewPaths([stripe]);assert.equal(p.files[0].source,'stripe');assert.equal(p.transactionCount,23);assert.equal(p.files[0].transactions.reduce((s,t)=>s+t.amountCents,0),502242)});
test('real Xero payslip preserves gross, PAYG, super and net',async()=>{const p=await previewPaths([payslip]);const t=p.files[0].transactions[0];assert.equal(t.amountCents,59200);assert.deepEqual({gross:t.metadata.grossCents,payg:t.metadata.paygCents,super:t.metadata.superCents},{gross:72000,payg:12800,super:8640})});
test('real ING statement reconciles and Stripe deposits are transfers',async()=>{const p=await previewPaths([bank]);const f=p.files[0];assert.equal(f.transactions.length,197);assert.deepEqual(f.balances,{openingCents:57810,closingCents:121419,movementCents:63609});assert.equal(f.transactions.filter(t=>/^STRIPE\b/.test(t.description)).length,23);assert.ok(f.transactions.filter(t=>/^STRIPE\b/.test(t.description)).every(t=>t.kind==='transfer'&&!t.profitIncluded))});
test('same-input multi-file preview matches 23 Stripe settlements',async()=>{const p=await previewPaths([stripe,bank]);assert.equal(p.matchedSettlements,23)});
test('database import is atomic, duplicate safe, editable and undoable',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-v2-'));const store=new FinanceStore(path.join(dir,'test.sqlite'));try{const p=await store.preview([stripe]);store.confirm(p);assert.equal(store.transactions({month:'2026-07'}).length,23);assert.equal(store.dashboard('2026-07').summary.businessProfit,502242);const duplicate=await store.preview([stripe]);assert.equal(duplicate.transactionCount,0);const manual=store.createTransaction({date:'2026-07-31',description:'Affiliate commission',amountCents:12345,kind:'income',scope:'business_affiliate',category:'Affiliate Marketing Income',reviewStatus:'confirmed',profitIncluded:true,note:''});assert.equal(store.dashboard('2026-07').summary.businessProfit,514587);store.updateTransaction({...manual,amountCents:20000});assert.equal(store.dashboard('2026-07').summary.businessProfit,522242);const importId=store.imports()[0].id;store.undoImport(importId);assert.equal(store.transactions({month:'2026-07'}).length,1);assert.equal(store.dashboard('2026-07').summary.businessProfit,20000)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});
test('profit guard rejects personal inclusion',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-v2-'));const store=new FinanceStore(path.join(dir,'test.sqlite'));try{assert.throws(()=>store.createTransaction({date:'2026-07-01',description:'Personal gift',amountCents:10000,kind:'income',scope:'personal',category:'Personal',reviewStatus:'confirmed',profitIncluded:true,note:''}),/Only confirmed PT or affiliate/)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('backup and restore replace the workspace only after integrity validation',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-v2-'));const db=path.join(dir,'live.sqlite'),backup=path.join(dir,'backup.sqlite');const store=new FinanceStore(db);try{store.createTransaction({date:'2026-07-01',description:'Before backup',amountCents:10000,kind:'income',scope:'business_affiliate',category:'Affiliate Marketing Income',reviewStatus:'confirmed',profitIncluded:true,note:''});store.backup(backup);store.createTransaction({date:'2026-07-02',description:'After backup',amountCents:5000,kind:'income',scope:'business_affiliate',category:'Affiliate Marketing Income',reviewStatus:'confirmed',profitIncluded:true,note:''});assert.equal(store.transactions({month:'2026-07'}).length,2);store.restore(backup);assert.equal(store.transactions({month:'2026-07'}).length,1);assert.equal(store.dashboard('2026-07').summary.businessProfit,10000)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('remembered review choice is applied to the same description next time',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-v2-'));const store=new FinanceStore(path.join(dir,'test.sqlite'));try{const p=await store.preview([bank]);store.confirm(p);const row=store.transactions({reviewStatus:'needs_review'}).find(t=>t.description==='DRIVERSNOTE');assert.ok(row);store.updateTransaction({...row,kind:'expense',scope:'business_pt',category:'Software',reviewStatus:'confirmed',profitIncluded:true,rememberRule:true});store.undoImport(store.imports()[0].id);const next=await store.preview([bank]);const remembered=next.files[0].transactions.find(t=>t.description==='DRIVERSNOTE');assert.equal(remembered.reviewStatus,'confirmed');assert.equal(remembered.category,'Software');assert.equal(remembered.profitIncluded,true)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

const syntheticRoot=path.resolve('test-fixtures/synthetic');
const syntheticManifest=JSON.parse(fs.readFileSync(path.join(syntheticRoot,'manifest.json'),'utf8'));
const syntheticPaths=month=>Object.values(syntheticManifest.months[month].files).map(file=>path.join(syntheticRoot,file.path));

test('three synthetic months parse and reconcile against their manifest',async()=>{for(const [month,spec] of Object.entries(syntheticManifest.months)){for(const file of Object.values(spec.files)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(syntheticRoot,file.path))).digest('hex'),file.sha256)}const preview=await previewPaths(syntheticPaths(month));const expected=spec.expected;const stripeFile=preview.files.find(f=>f.source==='stripe'),xeroFile=preview.files.find(f=>f.source==='xero'),bankFile=preview.files.find(f=>f.source==='ing');assert.equal(stripeFile.transactions.length,expected.stripeRows);assert.equal(stripeFile.transactions.reduce((sum,t)=>sum+t.amountCents,0),expected.stripeTotalCents);assert.equal(xeroFile.transactions[0].amountCents,expected.xeroNetCents);assert.equal(xeroFile.transactions[0].metadata.grossCents,expected.xeroGrossCents);assert.equal(xeroFile.transactions[0].metadata.paygCents,expected.xeroPaygCents);assert.equal(xeroFile.transactions[0].metadata.superCents,expected.xeroSuperCents);assert.equal(bankFile.transactions.length,expected.bankRows);assert.deepEqual(bankFile.balances,{openingCents:expected.bankOpeningCents,closingCents:expected.bankClosingCents,movementCents:expected.bankMovementCents});assert.equal(preview.matchedSettlements,expected.stripeMatches);assert.equal(preview.matchedEmployment,expected.employmentMatches);assert.equal(bankFile.transactions.filter(t=>t.metadata.matchedXeroKey).length,1)}});

test('synthetic multi-month import drives correct dashboard months without payout duplication',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-synthetic-')),store=new FinanceStore(path.join(dir,'test.sqlite'));try{const allPaths=Object.keys(syntheticManifest.months).flatMap(syntheticPaths);const preview=await store.preview(allPaths);assert.equal(preview.transactionCount,80);assert.equal(preview.matchedSettlements,24);assert.equal(preview.matchedEmployment,3);store.confirm(preview);for(const [month,spec] of Object.entries(syntheticManifest.months)){const dashboard=store.dashboard(month);assert.equal(dashboard.summary.businessProfit,spec.expected.stripeTotalCents);assert.equal(dashboard.summary.cashRemaining,spec.expected.bankMovementCents);assert.equal(dashboard.summary.cashIn-dashboard.summary.cashOut,spec.expected.bankMovementCents);const payroll=store.transactions({month}).find(t=>/PAYROLL/.test(t.description));assert.equal(payroll.kind,'transfer');assert.equal(payroll.reviewStatus,'confirmed')}const duplicate=await store.preview(allPaths);assert.equal(duplicate.transactionCount,0)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});
