import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {FinanceStore} from '../electron/store.mjs';import {previewPaths,__test} from '../electron/importers.mjs';
const synthetic=path.resolve('test-fixtures/synthetic');const aug=[path.join(synthetic,'2026-08','Stripe_Itemised_Payouts_2026-08.csv'),path.join(synthetic,'2026-08','Xero_Payslip_2026-08.pdf'),path.join(synthetic,'2026-08','ING_Orange_Everyday_2026-08.pdf')];
const tempStore=()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-edge-'));return {dir,store:new FinanceStore(path.join(dir,'data.sqlite'))}};const manual=(overrides={})=>({date:'2026-08-10',description:'Synthetic manual item',amountCents:10000,kind:'income',scope:'business_affiliate',category:'Affiliate Marketing Income',reviewStatus:'confirmed',profitIncluded:true,note:'test',...overrides});

test('undo then re-import of the identical file succeeds exactly once',async()=>{const {dir,store}=tempStore();try{store.confirm(await store.preview([aug[0]]));const first=store.imports()[0];assert.equal(store.transactions({month:'2026-08'}).length,8);store.undoImport(first.id);assert.equal(store.transactions({month:'2026-08'}).length,0);const again=await store.preview([aug[0]]);assert.equal(again.transactionCount,8);store.confirm(again);assert.equal(store.transactions({month:'2026-08'}).length,8);assert.equal(store.imports().length,1);assert.equal(store.imports()[0].revertedAt,null)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('same source identities in a differently hashed file roll back atomically',async()=>{const {dir,store}=tempStore();try{store.confirm(await store.preview([aug[0]]));const altered=path.join(dir,'altered.csv');fs.writeFileSync(altered,fs.readFileSync(aug[0],'utf8')+'\n');const before=store.imports().length;const preview=await store.preview([altered]);assert.equal(preview.transactionCount,8);assert.throws(()=>store.confirm(preview),/UNIQUE constraint failed: transactions.source_key/);assert.equal(store.imports().length,before);assert.equal(store.transactions({month:'2026-08'}).length,8)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('unsupported, malformed, corrupt, and mixed invalid files fail before database mutation',async()=>{const {dir,store}=tempStore();try{const txt=path.join(dir,'bad.txt'),csv=path.join(dir,'bad.csv'),pdf=path.join(dir,'bad.pdf');fs.writeFileSync(txt,'unsupported');fs.writeFileSync(csv,'date,amount\n2026-08-01,1');fs.writeFileSync(pdf,'not a pdf');await assert.rejects(()=>store.preview([txt]),/only CSV and text-based PDF/);await assert.rejects(()=>store.preview([csv]),/supported Stripe/);await assert.rejects(()=>store.preview([pdf]));await assert.rejects(()=>store.preview([aug[0],pdf]));assert.equal(store.imports().length,0);assert.equal(store.transactions({}).length,0)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('bank balance mismatch is detected by the parser',async()=>{const pages=await __test.pdfRows(fs.readFileSync(aug[2]));const transactionRow=pages.flat().find(r=>r.cells.some(c=>c.text==='EVERFIT'));const amount=transactionRow.cells.find(c=>c.x>=330&&c.x<500);amount.text='-$298.00';assert.throws(()=>__test.parseBank(pages),/reconciliation failed/)});

test('manual transaction CRUD changes calculations and imported row deletion is blocked',async()=>{const {dir,store}=tempStore();try{const created=store.createTransaction(manual());assert.equal(store.dashboard('2026-08').summary.businessProfit,10000);const updated=store.updateTransaction({...created,amountCents:17550,category:'Other Income',note:'updated'});assert.equal(updated.amountCents,17550);assert.equal(store.transactions({search:'updated'}).length,1);store.deleteTransaction(created.id);assert.equal(store.transactions({search:'Synthetic manual'}).length,0);store.confirm(await store.preview([aug[0]]));const imported=store.transactions({month:'2026-08'})[0];assert.throws(()=>store.deleteTransaction(imported.id),/Undo Import/)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('invalid transaction and unsafe profit inclusion leave no mutation',()=>{const {dir,store}=tempStore();try{assert.throws(()=>store.createTransaction(manual({description:''})),/required/);assert.throws(()=>store.createTransaction(manual({scope:'personal'})),/Only confirmed/);assert.throws(()=>store.createTransaction(manual({kind:'transfer'})),/Only confirmed/);assert.equal(store.transactions({}).length,0)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('transaction filters return only matching month, kind, scope, category and review state',async()=>{const {dir,store}=tempStore();try{store.confirm(await store.preview(aug));const byMonth=store.transactions({month:'2026-08'});assert.ok(byMonth.length>0&&byMonth.every(t=>t.month==='2026-08'));const income=store.transactions({kind:'income'});assert.ok(income.length>0&&income.every(t=>t.kind==='income'));const employment=store.transactions({scope:'employment'});assert.ok(employment.length>=2&&employment.every(t=>t.scope==='employment'));const review=store.transactions({reviewStatus:'needs_review'});assert.equal(review.length,9);assert.ok(review.every(t=>t.reviewStatus==='needs_review'));assert.equal(store.transactions({search:'definitely absent'}).length,0);const dashboard=store.dashboard('2026-08'),cashIn=store.transactions({month:'2026-08',cashDirection:'in'}),cashOut=store.transactions({month:'2026-08',cashDirection:'out'}),profit=store.transactions({month:'2026-08',profitIncluded:true}),cashFlow=store.transactions({month:'2026-08',cashFlow:true});assert.equal(cashIn.reduce((s,t)=>s+t.amountCents,0),dashboard.summary.cashIn);assert.equal(-cashOut.reduce((s,t)=>s+t.amountCents,0),dashboard.summary.cashOut);assert.equal(profit.reduce((s,t)=>s+t.amountCents,0),dashboard.summary.businessProfit);assert.equal(cashFlow.reduce((s,t)=>s+t.amountCents,0),dashboard.summary.cashRemaining)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('allocation validation, effective dating, rounding, and non-positive profit are safe',()=>{const {dir,store}=tempStore();try{assert.throws(()=>store.saveSettings({allocation:{effectiveMonth:'2026-09',ownersPay:30,tax:25,savings:10,investments:10,education:5,travel:5,creditCardDebt:14}}),/exactly 100/);store.saveSettings({allocation:{effectiveMonth:'2026-09',ownersPay:25,tax:25,savings:15,investments:10,education:5,travel:5,creditCardDebt:15}});assert.equal(store.allocationFor('2026-08').ownersPay,30);assert.equal(store.allocationFor('2026-09').ownersPay,25);store.createTransaction(manual({date:'2026-09-01',amountCents:10001}));const positive=store.dashboard('2026-09');assert.equal(positive.allocations.reduce((s,a)=>s+a.value,0),10001);store.createTransaction(manual({date:'2026-10-01',description:'Loss',amountCents:-20000,kind:'expense',category:'Marketing'}));assert.ok(store.dashboard('2026-10').allocations.every(a=>a.value===0))}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('financial snapshot create and update stores AUD cents and exact net worth',()=>{const {dir,store}=tempStore();try{store.saveSnapshot({month:'2026-08',savingsCents:100000,investmentsCents:200000,superCents:300000,otherAssetsCents:50000,creditCardCents:25000,loansCents:75000,otherLiabilitiesCents:10000,note:'first'});assert.equal(store.dashboard('2026-08').financial.netWorthCents,540000);store.saveSnapshot({month:'2026-08',savingsCents:150000,investmentsCents:200000,superCents:300000,otherAssetsCents:50000,creditCardCents:25000,loansCents:75000,otherLiabilitiesCents:10000,note:'updated'});assert.equal(store.dashboard('2026-08').financial.netWorthCents,590000);assert.equal(store.db.prepare('SELECT COUNT(*) n FROM snapshots').get().n,1)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('persistence survives reopen and trend remains chronological',async()=>{const {dir,store}=tempStore();const dbPath=store.dbPath;try{for(const month of ['2026-08','2026-09','2026-10']){const files=['Stripe_Itemised_Payouts_','Xero_Payslip_','ING_Orange_Everyday_'].map(prefix=>path.join(synthetic,month,`${prefix}${month}${prefix.startsWith('Stripe')?'.csv':'.pdf'}`));store.confirm(await store.preview(files))}store.close();const reopened=new FinanceStore(dbPath);try{assert.deepEqual(reopened.bootstrap().months,['2026-10','2026-09','2026-08']);assert.deepEqual(reopened.dashboard('2026-10').trend.map(x=>x.month),['2026-08','2026-09','2026-10'])}finally{reopened.close()}}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('invalid restore is rejected and current data remains intact',()=>{const {dir,store}=tempStore();try{store.createTransaction(manual());const invalid=path.join(dir,'invalid.sqlite');fs.writeFileSync(invalid,'not sqlite');assert.throws(()=>store.restore(invalid));assert.equal(store.transactions({}).length,1)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('undo removes only its batch and preserves manual and neighboring imports',async()=>{const {dir,store}=tempStore();try{store.confirm(await store.preview([aug[0],aug[1]]));const manualTx=store.createTransaction(manual());const stripeImport=store.imports().find(i=>i.source==='stripe');store.undoImport(stripeImport.id);assert.equal(store.transactions({month:'2026-08'}).filter(t=>t.sourceKey.startsWith('stripe:')).length,0);assert.ok(store.transactions({month:'2026-08'}).some(t=>t.id===manualTx.id));assert.ok(store.transactions({month:'2026-08'}).some(t=>t.scope==='employment'))}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('impossible Xero and ING calendar dates fail during preview parsing',async()=>{const payslipPages=[[{cells:[{text:'Pay Period: 01/02/2026 - 28/02/2026 Payment Date: 31/02/2026 Total Earnings: $100.00 Net Pay: $80.00 PAYG $20.00 SGC $10.00'}]}]];assert.throws(()=>__test.parsePayslip(payslipPages),/real payment period\/date/);const bankPages=await __test.pdfRows(fs.readFileSync(aug[2])),transactionRow=bankPages.flat().find(row=>row.cells.some(cell=>cell.x<100&&/^\d{2} [A-Z][a-z]{2} \d{4}$/.test(cell.text))),dateCell=transactionRow.cells.find(cell=>cell.x<100&&/^\d{2} [A-Z][a-z]{2} \d{4}$/.test(cell.text));dateCell.text='31 Feb 2026';assert.throws(()=>__test.parseBank(bankPages),/impossible transaction date/)});

test('imported source facts and authoritative matches cannot be edited',async()=>{const {dir,store}=tempStore();try{store.confirm(await store.preview(aug));const imported=store.transactions({month:'2026-08'}).find(tx=>tx.sourceKey.startsWith('stripe:')),payroll=store.transactions({month:'2026-08'}).find(tx=>tx.metadata.matchedXeroKey);assert.throws(()=>store.updateTransaction({...imported,amountCents:imported.amountCents+1}),/source file/);assert.throws(()=>store.updateTransaction({...imported,date:'2026-08-25'}),/source file/);assert.throws(()=>store.updateTransaction({...payroll,kind:'income',scope:'employment'}),/Matched transfers/);assert.equal(store.transactions({}).find(tx=>tx.id===imported.id).amountCents,imported.amountCents);assert.equal(store.transactions({}).find(tx=>tx.id===payroll.id).kind,'transfer')}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('undo and re-import of Xero rematches the persisted bank counterpart',async()=>{const {dir,store}=tempStore();try{store.confirm(await store.preview([aug[1],aug[2]]));const xeroImport=store.imports().find(item=>item.source==='xero');store.undoImport(xeroImport.id);let payroll=store.transactions({month:'2026-08'}).find(tx=>/PAYROLL/.test(tx.description));assert.equal(payroll.kind,'unknown');const preview=await store.preview([aug[1]]);assert.equal(preview.matchedEmployment,1);assert.equal(preview.counterpartUpdates.length,1);store.confirm(preview);payroll=store.transactions({month:'2026-08'}).find(tx=>/PAYROLL/.test(tx.description));assert.equal(payroll.kind,'transfer');assert.equal(payroll.reviewStatus,'confirmed');assert.ok(payroll.metadata.matchedXeroKey);const activeKeys=new Set(store.transactions({}).map(tx=>tx.sourceKey));assert.equal(activeKeys.has(payroll.metadata.matchedXeroKey),true)}finally{store.close();fs.rmSync(dir,{recursive:true,force:true})}});
