import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';import {_electron as electron} from 'playwright';
const require=createRequire(import.meta.url),electronPath=require('electron'),project=path.resolve('.'),synthetic=path.join(project,'test-fixtures','synthetic');
const files=month=>[path.join(synthetic,month,`Stripe_Itemised_Payouts_${month}.csv`),path.join(synthetic,month,`Xero_Payslip_${month}.pdf`),path.join(synthetic,month,`ING_Orange_Everyday_${month}.pdf`)];
const metricValues=page=>page.locator('.import-metrics strong').allTextContents();
async function stubOpen(app,filePaths){await app.evaluate(({dialog},paths)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:paths})},filePaths)}
async function stubSave(app,filePath){await app.evaluate(({dialog},target)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:target})},filePath)}
async function launch(dataDir){return electron.launch({executablePath:process.env.JERRI_ELECTRON_EXECUTABLE||electronPath,args:process.env.JERRI_PACKAGED==='1'?[]:[path.join(project,'electron','main.mjs')],env:{...process.env,JERRI_DATA_DIR:dataDir}})}

test('complete production Electron user journey', {timeout:180000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-electron-e2e-')),dataDir=path.join(root,'data'),backup=path.join(root,'accepted-backup.sqlite');let app;try{
 app=await launch(dataDir);const page=await app.firstWindow();const runtimeErrors=[];page.on('pageerror',e=>runtimeErrors.push(e.message));await page.waitForLoadState('domcontentloaded');
 assert.equal(await page.title(),'Jerri Finance');await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();assert.equal(await page.locator('.empty').isVisible(),true);assert.deepEqual(await page.evaluate(()=>({require:typeof globalThis.require,process:typeof globalThis.process,csp:document.querySelector('meta[http-equiv="Content-Security-Policy"]')?.content})),{require:'undefined',process:'undefined',csp:"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data:; connect-src 'self'"});
 // Invalid native import shows a visible error and preserves the empty workspace.
 const badPdf=path.join(root,'corrupt.pdf');fs.writeFileSync(badPdf,'not a pdf');await stubOpen(app,[badPdf]);await page.getByRole('button',{name:'Add files',exact:true}).click();await page.locator('.banner.error').waitFor();assert.equal(await page.locator('.empty').isVisible(),true);await page.locator('.banner.error button').click();
 // Native Add Files -> staged preview -> confirm.
 await stubOpen(app,files('2026-08'));await page.getByRole('button',{name:'Add files',exact:true}).click();await page.getByRole('heading',{name:'Everything checked before it changes'}).waitFor();assert.deepEqual(await metricValues(page),['3','27','9','9']);assert.equal(await page.locator('.file-list>div').count(),3);await page.getByRole('button',{name:'Confirm import'}).click();await page.locator('.summary-grid').waitFor();assert.deepEqual(await page.locator('.summary strong').allTextContents(),['$2,860','$997','$1,470','$1,863']);assert.match(await page.locator('.attention strong').innerText(),/^9 transactions/);await page.locator('.summary').first().click();await page.getByRole('heading',{name:'Every dollar, easy to trace.'}).waitFor();assert.equal(await page.locator('.tr:not(.th)').count(),10);assert.equal(await page.getByLabel('Transaction month').inputValue(),'2026-08');await page.getByText('Cash in',{exact:true}).waitFor();await page.getByRole('button',{name:'Clear filters'}).click();await page.waitForFunction(()=>document.querySelectorAll('.tr:not(.th)').length===27);assert.equal(await page.locator('.active-filters').count(),0);await page.getByRole('button',{name:'Dashboard',exact:true}).click();
 // Duplicate preview is non-mutating.
 await stubOpen(app,files('2026-08'));await page.getByRole('button',{name:'Add files',exact:true}).click();await page.getByRole('heading',{name:'Everything checked before it changes'}).waitFor();assert.deepEqual(await metricValues(page),['3','0','0','0']);assert.equal(await page.getByRole('button',{name:'Confirm import'}).isDisabled(),true);await page.getByRole('button',{name:'Cancel'}).click();
 // Review one imported record and remember the rule.
 await page.locator('.attention').click();await page.getByRole('heading',{name:'Every dollar, easy to trace.'}).waitFor();assert.equal(await page.locator('.tr:not(.th)').count(),9);await page.locator('.tr:not(.th)').filter({hasText:'EVERFIT'}).click();assert.equal(await page.getByLabel('Date').isDisabled(),true);assert.equal(await page.getByLabel('Amount (AUD)').isDisabled(),true);assert.equal(await page.getByLabel('Description',{exact:true}).isDisabled(),true);await page.getByLabel('What is it?').selectOption('expense');await page.getByLabel('Belongs to').selectOption('business_pt');await page.getByLabel('Category').fill('Software');await page.getByLabel('Include in business profit').check();await page.getByLabel('Use this choice next time').check();await page.getByRole('button',{name:'Save transaction'}).click();await page.locator('.modal').waitFor({state:'detached'});assert.equal(await page.locator('.tr:not(.th)').count(),8);
 // Manual affiliate CRUD through visible UI.
 await page.getByRole('button',{name:'Add manually'}).click();await page.getByLabel('Date').fill('2026-08-20');await page.getByLabel('Amount (AUD)').fill('450.25');await page.getByLabel('Description').fill('Synthetic affiliate bonus');await page.getByLabel('Note').fill('created in E2E');await page.getByRole('button',{name:'Save transaction'}).click();const search=page.getByPlaceholder('Search transactions');await search.fill('Synthetic affiliate bonus');await page.waitForTimeout(250);assert.equal(await page.locator('.tr:not(.th)').count(),1);await page.locator('.tr:not(.th)').click();await page.getByLabel('Amount (AUD)').fill('500.50');await page.getByLabel('Note').fill('updated in E2E');await page.getByRole('button',{name:'Save transaction'}).click();assert.match(await page.locator('.tr:not(.th)').innerText(),/\$500\.50/);await page.getByRole('button',{name:'Dashboard',exact:true}).click();assert.equal((await page.locator('.summary strong').nth(2).innerText()),'$1,671.50');await page.getByRole('button',{name:'Transactions',exact:true}).click();await page.locator('.tr:not(.th)').click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Delete'}).click();await page.waitForTimeout(250);assert.equal(await page.locator('.tr:not(.th)').count(),0);await search.fill('');
 // Allocation validation and effective-dated save.
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('heading',{name:'Simple setup, your way.'}).waitFor();const owner=page.getByRole('spinbutton',{name:"Owner's Pay %"}),savings=page.getByRole('spinbutton',{name:'Savings %'});await owner.fill('25');assert.equal(await page.getByRole('button',{name:'Save allocation'}).isDisabled(),true);await savings.fill('15');assert.equal(await page.getByRole('button',{name:'Save allocation'}).isEnabled(),true);await page.getByRole('button',{name:'Save allocation'}).click();await page.getByText('Allocation settings saved.').waitFor();
 // Snapshot UI uses dollars and computes exact net worth.
 const snapshotValues={Savings:'1000',Investments:'2000',Super:'3000','Other Assets':'500','Credit Card':'250',Loans:'750','Other Liabilities':'100'};for(const [name,value] of Object.entries(snapshotValues))await page.getByLabel(name,{exact:true}).fill(value);await page.getByRole('button',{name:'Save snapshot'}).click();await page.getByText('Financial position updated.').waitFor();await page.getByRole('button',{name:'Dashboard',exact:true}).click();await page.getByText('$5,400',{exact:true}).waitFor();await page.getByRole('button',{name:/Update balances/}).click();await page.getByRole('heading',{name:'Simple setup, your way.'}).waitFor();
 // Later months, learned rule, month switching and cash-flow trend.
 await stubOpen(app,[...files('2026-09'),...files('2026-10')]);await page.getByRole('button',{name:'Add files',exact:true}).click();await page.getByRole('heading',{name:'Everything checked before it changes'}).waitFor();assert.deepEqual(await metricValues(page),['6','53','18','15']);await page.getByRole('button',{name:'Confirm import'}).click();await page.locator('.summary-grid').waitFor();assert.equal(await page.locator('.period .month-picker-input').inputValue(),'2026-10');assert.equal(await page.locator('.cash-bars>div').count(),3);assert.deepEqual(await page.locator('.summary strong').allTextContents(),['$2,450','$1,375','$741','$1,075']);await page.locator('.period .month-picker-trigger').click();await page.getByRole('button',{name:'Sep',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.period .month-picker-input')?.value==='2026-09');assert.deepEqual(await page.locator('.summary strong').allTextContents(),['$3,015','$1,356','$1,621','$1,659']);
 // Payslip details and current selected-month propagation into Transactions.
 await page.locator('.period .month-picker-trigger').click();await page.getByRole('button',{name:'Oct',exact:true}).click();await page.getByRole('button',{name:'Transactions',exact:true}).click();await page.getByPlaceholder('Search transactions').fill('Employment pay');await page.waitForTimeout(250);assert.equal(await page.locator('.tr:not(.th)').count(),1);await page.locator('.tr:not(.th)').click();assert.deepEqual(await page.locator('.payslip-detail b').allTextContents(),['$1,180.00','$190.00','$141.60','$990.00']);await page.locator('.modal-head button').click();
 // Backup through native dialog, mutate, then restore through native dialog.
 await page.getByRole('button',{name:'Settings',exact:true}).click();await stubSave(app,backup);await page.getByRole('button',{name:'Save backup'}).click();await page.getByText('Backup saved.').waitFor();assert.equal(fs.existsSync(backup),true);await page.getByRole('button',{name:'Transactions',exact:true}).click();await page.getByRole('button',{name:'Add manually'}).click();await page.getByLabel('Date').fill('2026-10-30');await page.getByLabel('Amount (AUD)').fill('777');await page.getByLabel('Description').fill('Created after backup');await page.getByRole('button',{name:'Save transaction'}).click();assert.equal((await page.evaluate(()=>window.finance.transactions({search:'Created after backup'}))).length,1);await page.getByRole('button',{name:'Settings',exact:true}).click();await stubOpen(app,[backup]);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Restore backup'}).click();await page.getByText('Backup restored.').waitFor();assert.equal((await page.evaluate(()=>window.finance.transactions({search:'Created after backup'}))).length,0);
 // Undo one batch and re-import the same hash through UI.
 const stripe10='Stripe_Itemised_Payouts_2026-10.csv';const historyRow=page.locator('.history>div').filter({hasText:stripe10});page.once('dialog',d=>d.accept());await historyRow.getByRole('button',{name:'Undo import'}).click();await page.getByText('Import undone.').waitFor();assert.equal(await page.evaluate(()=>window.finance.transactions({month:'2026-10'}).then(xs=>xs.filter(t=>t.sourceKey.startsWith('stripe:')).length)),0);await stubOpen(app,[files('2026-10')[0]]);await page.getByRole('button',{name:'Add files',exact:true}).click();await page.getByRole('heading',{name:'Everything checked before it changes'}).waitFor();assert.deepEqual(await metricValues(page),['1','7','7','0']);await page.getByRole('button',{name:'Confirm import'}).click();assert.equal(await page.evaluate(()=>window.finance.transactions({month:'2026-10'}).then(xs=>xs.filter(t=>t.sourceKey.startsWith('stripe:')).length)),7);
 // All screens remain usable and no renderer exceptions occurred.
 await page.getByRole('button',{name:'Dashboard',exact:true}).click();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();assert.deepEqual(runtimeErrors,[]);await page.screenshot({path:path.join(project,'analysis',process.env.JERRI_PACKAGED==='1'?'e2e-packaged-final.png':'e2e-source-final.png'),fullPage:true});await app.close();app=null;
 // Restart proves persistence.
 app=await launch(dataDir);const restarted=await app.firstWindow();await restarted.getByRole('heading',{name:'Your money, made clear.'}).waitFor();assert.match(await restarted.locator('.period .month-picker-trigger').innerText(),/October 2026/);assert.deepEqual(await restarted.locator('.summary strong').allTextContents(),['$2,450','$1,375','$741','$1,075']);
 }finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});
