import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {_electron as electron} from 'playwright';

const require=createRequire(import.meta.url),electronPath=require('electron'),project=path.resolve('.');
async function launch(dataDir){return electron.launch({executablePath:process.env.JERRI_ELECTRON_EXECUTABLE||electronPath,args:process.env.JERRI_PACKAGED==='1'?[]:[path.join(project,'electron','main.mjs')],env:{...process.env,JERRI_DATA_DIR:dataDir}})}
async function cancelOpen(app){await app.evaluate(({dialog})=>{dialog.showOpenDialog=async()=>({canceled:true,filePaths:[]})})}
async function cancelSave(app){await app.evaluate(({dialog})=>{dialog.showSaveDialog=async()=>({canceled:true})})}
async function stubOpen(app,filePaths){await app.evaluate(({dialog},paths)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:paths})},filePaths)}

const closeGlobalError=async page=>{const banner=page.locator('main>.banner.error');if(await banner.isVisible())await banner.getByRole('button').click()};

test('adversarial UI state, validation, cancel, retry, and snapshot lifecycle', {timeout:120000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-electron-adversarial-')),dataDir=path.join(root,'data');let app;try{
 app=await launch(dataDir);const page=await app.firstWindow(),runtimeErrors=[];page.on('pageerror',error=>runtimeErrors.push(error.message));await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();
 // Native file-dialog cancellation is a true no-op.
 await cancelOpen(app);await page.getByRole('button',{name:'Add files',exact:true}).click();await page.waitForTimeout(100);assert.equal(await page.locator('.modal').count(),0);assert.equal(await page.locator('.empty').isVisible(),true);
 // Invalid manual amount stays in the editor and produces no hidden write.
 await page.getByRole('button',{name:'Transactions',exact:true}).click();await page.getByRole('button',{name:'Add manually'}).click();await page.getByLabel('Date').fill('2026-08-10');await page.getByLabel('Description').fill('Expense sign contract');await page.getByLabel('What is it?').selectOption('expense');await page.getByLabel('Category').fill('Software');await page.getByLabel('Amount (AUD)').fill('25');await page.getByRole('button',{name:'Save transaction'}).click();await page.locator('.modal .banner.error').waitFor();assert.match(await page.locator('.modal .banner.error').innerText(),/expenses must use a minus amount/i);assert.equal((await page.evaluate(()=>window.finance.transactions({}))).length,0);await page.getByLabel('Amount (AUD)').fill('-25.001');await page.getByRole('button',{name:'Save transaction'}).click();assert.match(await page.locator('.modal .banner.error').innerText(),/two decimal places/i);assert.equal((await page.evaluate(()=>window.finance.transactions({}))).length,0);await page.getByLabel('Amount (AUD)').fill('-25');await page.getByRole('button',{name:'Save transaction'}).click();await page.locator('.modal').waitFor({state:'detached'});assert.equal((await page.evaluate(()=>window.finance.transactions({}))).length,1);
 // Literal wildcard search and clear-filters behavior remain visible and deterministic.
 const search=page.getByPlaceholder('Search transactions');await search.fill('%');await page.waitForTimeout(200);assert.equal(await page.locator('.tr:not(.th)').count(),0);await page.getByRole('button',{name:'Clear filters'}).click();await page.waitForTimeout(200);assert.equal(await page.locator('.tr:not(.th)').count(),1);
 // Backend rejects an allocation that totals 100 but contains out-of-range values; UI catches it.
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByText('No imports yet.').waitFor();await page.getByRole('spinbutton',{name:"Owner's Pay %"}).fill('130');await page.getByRole('spinbutton',{name:'Tax %'}).fill('-75');assert.equal(await page.getByRole('button',{name:'Save allocation'}).isEnabled(),true);await page.getByRole('button',{name:'Save allocation'}).click();await page.locator('main>.banner.error').waitFor();assert.match(await page.locator('main>.banner.error').innerText(),/values from 0 to 100/i);assert.equal((await page.evaluate(()=>window.finance.allocationFor('2026-08'))).ownersPay,30);await closeGlobalError(page);
 // A valid future profile can be saved and loaded again when changing effective month.
 const allocationMonth=page.getByLabel('Effective month');await allocationMonth.fill('2027-01');for(const [name,value] of [["Owner's Pay %",'25'],['Tax %','25'],['Savings %','15'],['Investments %','10'],['Education %','5'],['Travel %','5'],['Credit Card Debt %','15']])await page.getByRole('spinbutton',{name}).fill(value);await page.getByRole('button',{name:'Save allocation'}).click();await page.getByText('Allocation settings saved.').waitFor();await allocationMonth.fill('2026-12');await page.getByRole('spinbutton',{name:"Owner's Pay %"}).waitFor();await page.waitForFunction(()=>document.querySelector('input[aria-label="never"]')===null);await page.waitForTimeout(100);assert.equal(await page.getByRole('spinbutton',{name:"Owner's Pay %"}).inputValue(),'30');await allocationMonth.fill('2027-01');await page.waitForTimeout(100);assert.equal(await page.getByRole('spinbutton',{name:"Owner's Pay %"}).inputValue(),'25');
 // Save a snapshot-only month; it becomes navigable, then reload exact values without wiping siblings.
 const snapshotMonth=page.getByLabel('Snapshot month');await snapshotMonth.fill('2027-02');const values={Savings:'1000',Investments:'2000',Super:'3000','Other Assets':'500','Credit Card':'250',Loans:'750','Other Liabilities':'100'};for(const [name,value] of Object.entries(values))await page.getByLabel(name,{exact:true}).fill(value);await page.getByLabel('Snapshot note').fill('adversarial snapshot');await page.getByRole('button',{name:'Save snapshot'}).click();await page.getByText('Financial position updated.').waitFor();await page.getByRole('button',{name:'Dashboard',exact:true}).click();assert.equal(await page.locator('.period .month-picker-input').inputValue(),'2027-02');await page.locator('.panel.position').waitFor();assert.equal(await page.locator('.panel.position h2').innerText(),'$5,400');await page.getByRole('button',{name:/Update balances/}).click();await page.waitForTimeout(150);assert.equal(await page.getByLabel('Savings',{exact:true}).inputValue(),'1000');assert.equal(await page.getByLabel('Investments',{exact:true}).inputValue(),'2000');assert.equal(await page.getByLabel('Snapshot note').inputValue(),'adversarial snapshot');await page.getByLabel('Savings',{exact:true}).fill('1500');await page.getByRole('button',{name:'Save snapshot'}).click();await page.getByText('Financial position updated.').waitFor();const snapshot=await page.evaluate(()=>window.finance.snapshotFor('2027-02'));assert.equal(snapshot.savingsCents,150000);assert.equal(snapshot.investmentsCents,200000);assert.equal(snapshot.superCents,300000);
 // Invalid snapshot does not mutate existing values and the action can be retried.
 await page.getByLabel('Savings',{exact:true}).fill('-1');await page.getByRole('button',{name:'Save snapshot'}).click();await page.locator('main>.banner.error').waitFor();assert.equal((await page.evaluate(()=>window.finance.snapshotFor('2027-02'))).savingsCents,150000);await closeGlobalError(page);await page.getByLabel('Savings',{exact:true}).fill('1600.001');await page.getByRole('button',{name:'Save snapshot'}).click();await page.locator('main>.banner.error').waitFor();assert.match(await page.locator('main>.banner.error').innerText(),/two decimal places/i);assert.equal((await page.evaluate(()=>window.finance.snapshotFor('2027-02'))).savingsCents,150000);await closeGlobalError(page);await page.getByLabel('Savings',{exact:true}).fill('1600');await page.getByRole('button',{name:'Save snapshot'}).click();await page.getByText('Financial position updated.').waitFor();assert.equal((await page.evaluate(()=>window.finance.snapshotFor('2027-02'))).savingsCents,160000);
 // Backup cancellation and structurally invalid restore are recoverable UI paths.
 await cancelSave(app);await page.getByRole('button',{name:'Save backup'}).click();await page.waitForTimeout(100);assert.equal(await page.getByText('Backup saved.').count(),0);const invalid=path.join(root,'invalid.sqlite');fs.writeFileSync(invalid,'SQLite format 3\0not really');await stubOpen(app,[invalid]);page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Restore backup'}).click();await page.locator('main>.banner.error').waitFor();assert.match(await page.locator('main>.banner.error').innerText(),/valid Jerri Finance backup/i);assert.equal((await page.evaluate(()=>window.finance.snapshotFor('2027-02'))).savingsCents,160000);assert.deepEqual(runtimeErrors,[]);
 }finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('individual and select-all review actions update only chosen transactions', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-bulk-review-')),dataDir=path.join(root,'data');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();const base={date:'2026-08-10',amountCents:-100,kind:'unknown',scope:'unknown',category:'Needs Review',reviewStatus:'needs_review',profitIncluded:false,note:''};await page.evaluate(async input=>{await window.finance.createTransaction({...input,description:'Review alpha'});await window.finance.createTransaction({...input,date:'2026-08-11',description:'Review beta'});await window.finance.createTransaction({...input,date:'2026-08-12',description:'Already done',reviewStatus:'confirmed'})},base);await page.getByRole('button',{name:'Transactions',exact:true}).click();await page.getByLabel('Transaction month').fill('2026-08');await page.getByLabel('Select Review alpha').check();await page.getByRole('button',{name:'Mark reviewed (1)'}).click();await page.getByText('1 transaction marked reviewed.').waitFor();let pending=await page.evaluate(()=>window.finance.transactions({reviewStatus:'needs_review'}));assert.deepEqual(pending.map(tx=>tx.description),['Review beta']);await page.getByRole('button',{name:'Select all'}).click();assert.equal(await page.getByLabel('Select Review beta').isChecked(),true);await page.getByRole('button',{name:'Mark reviewed (1)'}).click();await page.getByText('1 transaction marked reviewed.').waitFor();pending=await page.evaluate(()=>window.finance.transactions({reviewStatus:'needs_review'}));assert.equal(pending.length,0);assert.equal(await page.locator('.bulk-review').count(),0)}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('corrupt live workspace fails visibly and retry reopens a repaired workspace', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-corrupt-startup-')),dataDir=path.join(root,'data'),dbPath=path.join(dataDir,'jerri-finance.sqlite');fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(dbPath,'not a database');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:/couldn’t open Jerri Finance/i}).waitFor();assert.match(await page.locator('.fatal').innerText(),/Could not open the local finance workspace/i);assert.equal(await page.getByRole('button',{name:'Try again'}).isVisible(),true);fs.rmSync(dbPath);await page.getByRole('button',{name:'Try again'}).click();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();assert.equal(await page.locator('.empty').isVisible(),true)}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('production renderer blocks external navigation and popup creation', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-navigation-security-')),dataDir=path.join(root,'data');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();const deniedPermission=await page.evaluate(()=>new Promise(resolve=>navigator.geolocation.getCurrentPosition(()=>resolve(false),()=>resolve(true))));assert.equal(deniedPermission,true);const untrustedWindow=app.waitForEvent('window');await app.evaluate(async({BrowserWindow},preload)=>{const win=new BrowserWindow({show:false,webPreferences:{preload,contextIsolation:true,nodeIntegration:false,sandbox:true}});await win.loadURL('data:text/html,<title>Untrusted</title>')},path.join(project,'electron','preload.cjs'));const untrusted=await untrustedWindow;const ipcError=await untrusted.evaluate(()=>window.finance.bootstrap().then(()=>'',error=>error.message));assert.match(ipcError,/Untrusted renderer request blocked/);await untrusted.close();const forgedError=await page.evaluate(()=>window.finance.confirmImport('forged-preview').then(()=>'',error=>error.message));assert.match(forgedError,/expired|not created/i);const original=page.url();await page.evaluate(()=>{location.href='https://example.com/'});await page.waitForTimeout(250);assert.equal(page.url(),original);const popup=await page.evaluate(()=>window.open('https://example.com/'));assert.equal(popup,null)}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('amount entry formatting, friendly validation, and manual CRUD are customer-readable', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-money-crud-')),dataDir=path.join(root,'data');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await page.getByRole('button',{name:'Transactions',exact:true}).click();await page.getByRole('button',{name:'Add manually'}).click();const amount=page.getByLabel('Amount (AUD)');await amount.fill('022200');assert.equal(await amount.inputValue(),'22,200');await amount.fill('000200.50');assert.equal(await amount.inputValue(),'200.50');await amount.fill('-0200.50');assert.equal(await amount.inputValue(),'-200.50');await page.getByLabel('Date').fill('2026-08-25');await page.getByRole('button',{name:'Save transaction'}).click();const error=page.locator('.modal .banner.error');await error.waitFor();assert.match(await error.innerText(),/description/i);assert.doesNotMatch(await error.innerText(),/remote method|create-transaction|Error:/i);await page.getByRole('button',{name:'Cancel'}).click();await page.getByRole('button',{name:'Add manually'}).click();const freshAmount=page.getByLabel('Amount (AUD)');await page.getByLabel('Date').fill('2026-08-25');await page.getByLabel('Description').fill('Manual CRUD round trip');await page.getByRole('combobox',{name:'What is it?'}).selectOption('expense');await freshAmount.fill('25');await page.waitForTimeout(100);await page.getByRole('button',{name:'Save transaction'}).click();const freshError=page.locator('.modal .banner.error');await freshError.waitFor();assert.match(await freshError.innerText(),/expenses must use a minus amount/i);assert.doesNotMatch(await freshError.innerText(),/remote method|create-transaction|Error:/i);await freshAmount.fill('-25');await page.getByRole('button',{name:'Save transaction'}).click();await page.locator('.modal').waitFor({state:'detached'});assert.equal((await page.evaluate(()=>window.finance.transactions({search:'Manual CRUD round trip'}))).length,1);await page.locator('.tr:not(.th)').filter({hasText:'Manual CRUD round trip'}).click();await page.getByLabel('Category').fill('Updated category');await page.getByRole('button',{name:'Save transaction'}).click();await page.getByText('Transaction saved.').waitFor();assert.equal((await page.evaluate(()=>window.finance.transactions({search:'Manual CRUD round trip'})))[0].category,'Updated category');await page.locator('.tr:not(.th)').filter({hasText:'Manual CRUD round trip'}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete'}).click();await page.locator('.modal').waitFor({state:'detached'});assert.equal((await page.evaluate(()=>window.finance.transactions({search:'Manual CRUD round trip'}))).length,0)}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('settings category customization survives reload and protects used history', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-categories-')),dataDir=path.join(root,'data');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await page.getByRole('button',{name:'Settings',exact:true}).click();const input=page.getByLabel('New category');await input.fill('Home maintenance');await page.getByRole('button',{name:'Add category'}).click();await page.getByText('Category added.').waitFor();await page.getByText('Home maintenance',{exact:true}).waitFor();await page.evaluate(()=>window.finance.createTransaction({date:'2026-08-25',description:'Roof repair',amountCents:-12500,kind:'expense',scope:'personal',category:'Home maintenance',reviewStatus:'confirmed',profitIncluded:false,note:''}));await page.getByRole('button',{name:'Remove Home maintenance'}).click();await page.getByRole('alert').filter({hasText:'already used'}).waitFor();await page.evaluate(async()=>{const tx=(await window.finance.transactions({search:'Roof repair'}))[0];await window.finance.updateTransaction({...tx,category:'Personal'})});await page.getByRole('button',{name:'Remove Home maintenance'}).click();await page.getByText('Category removed.').waitFor();assert.equal((await page.evaluate(()=>window.finance.bootstrap())).settings.customCategories.includes('Home maintenance'),false)}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('month picker communicates empty, populated, and selected months visually', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-month-states-')),dataDir=path.join(root,'data');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await page.evaluate(async()=>{await window.finance.createTransaction({date:'2026-08-25',description:'Month state sample',amountCents:1000,kind:'income',scope:'business_affiliate',category:'Other Income',reviewStatus:'confirmed',profitIncluded:true,note:''})});await page.reload();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await page.locator('.month-picker-trigger').click();assert.match(await page.getByRole('button',{name:'Aug',exact:true}).getAttribute('class'),/has-data/);assert.doesNotMatch(await page.getByRole('button',{name:'Jan',exact:true}).getAttribute('class')||'',/has-data/);assert.match(await page.getByRole('button',{name:'Aug',exact:true}).getAttribute('class'),/selected/)}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('Insights, Ask Jerri setup boundary, and Goals are reachable customer workflows', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-new-tabs-')),dataDir=path.join(root,'data');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await page.getByRole('button',{name:'Insights',exact:true}).click();await page.getByRole('heading',{name:'No transaction data for this month'}).waitFor();await page.getByRole('button',{name:'Ask Jerri',exact:true}).click();await page.getByRole('heading',{name:'Ask Jerri',exact:true}).waitFor();await page.getByRole('button',{name:'Choose a local model'}).click();await page.getByRole('heading',{name:'Pick the right fit'}).waitFor();assert.equal(await page.getByRole('button',{name:/Download Qwen2.5 3B/}).isEnabled(),true);await page.getByRole('button',{name:'Close AI setup'}).click();await page.getByRole('button',{name:'Goals',exact:true}).click();await page.getByRole('heading',{name:'Create a goal'}).waitFor();await page.getByLabel('Goal name').fill('Emergency fund');const goalInputs=page.locator('.goal-editor input');await goalInputs.nth(1).fill('1,000');await page.getByRole('button',{name:'Create goal'}).click();await page.getByText('Goal created.').waitFor();await page.getByRole('heading',{name:'Emergency fund'}).waitFor();assert.match(await page.locator('.goal-card').innerText(),/0%/)}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});

test('Ask Jerri conversation manager, model manager, and send setup flow are usable', {timeout:60000}, async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'jerri-ask-manager-')),dataDir=path.join(root,'data');let app;try{app=await launch(dataDir);const page=await app.firstWindow();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await page.evaluate(()=>{localStorage.removeItem('jerri.ask.sessions');localStorage.removeItem('jerri.ask.active')});await page.reload();await page.getByRole('heading',{name:'Your money, made clear.'}).waitFor();await page.getByRole('button',{name:'Ask Jerri',exact:true}).click();await page.getByRole('heading',{name:'Ask Jerri',exact:true}).waitFor();assert.equal(await page.getByText('Conversations',{exact:true}).isVisible(),true);assert.equal(await page.getByText('Models',{exact:true}).isVisible(),true);assert.equal(await page.getByText('Qwen2.5 3B',{exact:true}).count(),1);assert.equal(await page.getByText('Gemma 3 1B',{exact:true}).count(),1);assert.equal(await page.getByText('Phi-4 Mini',{exact:true}).count(),1);await page.getByRole('button',{name:'New conversation',exact:true}).click();assert.equal(await page.locator('.conversation-item').count(),2);page.once('dialog',dialog=>dialog.accept());await page.locator('.conversation-row').first().locator('.conversation-delete').click();assert.equal(await page.locator('.conversation-item').count(),1);await page.getByRole('button',{name:'New conversation',exact:true}).click();await page.locator('.chat-composer textarea, .pre-setup-composer textarea').fill('What changed from last month?');assert.equal(await page.getByRole('button',{name:'Send question'}).isEnabled(),true);await page.getByRole('button',{name:'Send question'}).click();await page.getByRole('heading',{name:'Pick the right fit'}).waitFor();await page.getByRole('button',{name:'Close AI setup'}).click();await page.getByRole('button',{name:'Goals',exact:true}).click();await page.getByRole('heading',{name:'Create a goal'}).waitFor();await page.getByRole('button',{name:'Ask Jerri',exact:true}).click();assert.equal(await page.locator('.conversation-item').count(),2);assert.equal(await page.locator('.conversation-item').count(),2);await page.getByRole('button',{name:'Open model setup'}).click();await page.getByRole('heading',{name:'Pick the right fit'}).waitFor();await page.locator('.model-card').filter({hasText:'Gemma 3 1B'}).click();assert.equal(await page.getByRole('button',{name:/Download Gemma 3 1B/}).isEnabled(),true);await page.getByRole('button',{name:'Close AI setup'}).click()}finally{if(app)await app.close().catch(()=>{});fs.rmSync(root,{recursive:true,force:true})}});
