import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';
import {spawn} from 'node:child_process';
import https from 'node:https';
import http from 'node:http';

const RELEASE='b10516';
const MODELS=[
 {id:'qwen2.5-3b-q4_k_m',name:'Qwen2.5 3B',variant:'Q4_K_M',tag:'Balanced',description:'Strong everyday explanations with a good speed/quality balance.',sizeBytes:2100000000,sizeLabel:'about 2.1 GB',license:'qwen-research',source:'Qwen',url:'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf?download=true',sha256:'626b4a6678b86442240e33df819e00132d3ba7dddfe1cdc4fbb18e0a9615c62d'},
 {id:'gemma-3-1b-it-q4_k_m',name:'Gemma 3 1B',variant:'Q4_K_M',tag:'Lightest',description:'Smallest download for quicker setup and lower memory use.',sizeBytes:806000000,sizeLabel:'about 806 MB',license:'gemma',source:'Google / ggml-org',url:'https://huggingface.co/ggml-org/gemma-3-1b-it-GGUF/resolve/main/gemma-3-1b-it-Q4_K_M.gguf?download=true',sha256:'8ccc5cd1f1b3602548715ae25a66ed73fd5dc68a210412eea643eb20eb75a135'},
 {id:'phi-4-mini-q4_k_m',name:'Phi-4 Mini',variant:'Q4_K_M',tag:'Reasoning',description:'Larger local model for more detailed explanations; needs more memory.',sizeBytes:2490000000,sizeLabel:'about 2.49 GB',license:'MIT (model); community GGUF',source:'Microsoft / community GGUF',url:'https://huggingface.co/professorf/Phi-4-mini-instruct-gguf/resolve/main/Phi-4-mini-instruct-q4_k_m.gguf?download=true',sha256:'d422d18247fc1d8e8bc33138fdee087846a66183bc137fee6a3b4c540114eb91'}
];
const MODEL=MODELS[0];
const RUNTIMES={
 'darwin-arm64':{label:'macOS Apple Silicon',archive:`llama-${RELEASE}-bin-macos-arm64.tar.gz`,sha256:'ee3324327d621026ae80c24031670e65fa62a0b23a3a027dbe2f65f240affd30'},
 'darwin-x64':{label:'macOS Intel',archive:`llama-${RELEASE}-bin-macos-x64.tar.gz`,sha256:'b7adecf7bd2cde577ddabee8357a72409165d8104f43b4acee9f1b98cc9c447a'},
 'win32-x64':{label:'Windows x64',archive:`llama-${RELEASE}-bin-win-cpu-x64.zip`,sha256:'fbbbc55e0eb2e1b07f9dcb9488616c98ed47d9003b90e15e7c8c7812c4307cd3'},
};
const runtimeKey=()=>`${process.platform}-${process.arch}`;
const runtime=()=>RUNTIMES[runtimeKey()]||null;
const sha256=file=>new Promise((resolve,reject)=>{const hash=crypto.createHash('sha256');const stream=fs.createReadStream(file);stream.on('data',x=>hash.update(x));stream.on('error',reject);stream.on('end',()=>resolve(hash.digest('hex')))});
function download(url,target,expected,onProgress){return new Promise((resolve,reject)=>{fs.mkdirSync(path.dirname(target),{recursive:true});const temp=`${target}.part`;let received=0;const get=current=>{const client=current.startsWith('https:')?https:http;client.get(current,res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location)return get(new URL(res.headers.location,current).href);if(res.statusCode!==200)return reject(new Error(`Download failed with HTTP ${res.statusCode}.`));const total=Number(res.headers['content-length']||0),out=fs.createWriteStream(temp);res.on('data',chunk=>{received+=chunk.length;onProgress?.({received,total,percent:total?Math.round(received/total*100):null})});res.pipe(out);out.on('finish',async()=>{out.close(async()=>{try{const actual=await sha256(temp);if(actual!==expected){fs.rmSync(temp,{force:true});reject(new Error('Download checksum did not match the pinned release.'));return}fs.renameSync(temp,target);resolve(target)}catch(error){fs.rmSync(temp,{force:true});reject(error)}})});res.on('error',reject)}).on('error',reject)};get(url)})}
function extract(archive,dest){return new Promise((resolve,reject)=>{fs.mkdirSync(dest,{recursive:true});const isZip=archive.toLowerCase().endsWith('.zip'),quote=value=>`'${value.replaceAll("'","''")}'`,command=isZip?`Expand-Archive -LiteralPath ${quote(archive)} -DestinationPath ${quote(dest)} -Force`:null,args=isZip?['-NoProfile','-NonInteractive','-Command',command]:['-xzf',archive,'-C',dest],child=spawn(isZip?'powershell.exe':'tar',args,{stdio:'ignore'});child.on('error',()=>reject(new Error('The local archive extractor is unavailable on this computer.')));child.on('exit',code=>code===0?resolve():reject(new Error('The verified runtime archive could not be extracted.')))})}
function findServer(dir){if(!fs.existsSync(dir))return null;const name=process.platform==='win32'?'llama-server.exe':'llama-server';const found=[];const walk=d=>{for(const item of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,item.name);if(item.isDirectory())walk(p);else if(item.name===name)found.push(p)}};walk(dir);return found[0]||null}
export class AiManager{
 constructor(dataDir){this.root=path.join(dataDir,'ai');this.server=null;this.serverPort=null;}
 configPath(){return path.join(this.root,'config.json')}
 config(){try{return JSON.parse(fs.readFileSync(this.configPath(),'utf8'))}catch{return {selectedModelId:MODEL.id}}}
 selectedModel(){return MODELS.find(model=>model.id===this.config().selectedModelId)||MODEL}
 modelPath(model=this.selectedModel()){return path.join(this.root,'models',model.id+'.gguf')}
 state(){const r=runtime(),selected=this.selectedModel(),serverPath=r?findServer(path.join(this.root,'runtimes',RELEASE,runtimeKey())):null;return {models:MODELS.map(model=>({...model,installed:fs.existsSync(this.modelPath(model))})),model:selected,selectedModelId:selected.id,runtime:r?{...r,key:runtimeKey(),release:RELEASE,ready:Boolean(serverPath),serverPath}:null,modelReady:fs.existsSync(this.modelPath(selected)),ready:Boolean(serverPath&&fs.existsSync(this.modelPath(selected))),consentFile:fs.existsSync(path.join(this.root,'consent.json'))};}
 selectModel(modelId){const model=MODELS.find(item=>item.id===modelId);if(!model||!fs.existsSync(this.modelPath(model)))throw new Error('That model is not installed. Set it up before selecting it.');fs.mkdirSync(this.root,{recursive:true});fs.writeFileSync(this.configPath(),JSON.stringify({selectedModelId:model.id}));return this.state();}
 deleteModel(modelId){const model=MODELS.find(item=>item.id===modelId);if(!model)throw new Error('Model not found.');if(this.selectedModel().id===model.id&&this.server)throw new Error('Stop the local model before deleting the one currently in use.');fs.rmSync(this.modelPath(model),{force:true});if(this.selectedModel().id===model.id)fs.writeFileSync(this.configPath(),JSON.stringify({selectedModelId:MODEL.id}));return this.state();}
 async setup({modelId,onProgress}={}){const r=runtime(),selected=MODELS.find(model=>model.id===modelId)||this.selectedModel();if(!r)throw new Error(`This CPU architecture is not supported by the pinned llama.cpp runtime: ${runtimeKey()}.`);fs.mkdirSync(this.root,{recursive:true});fs.writeFileSync(this.configPath(),JSON.stringify({selectedModelId:selected.id},{indent:2}));fs.writeFileSync(path.join(this.root,'consent.json'),JSON.stringify({modelId:selected.id,license:selected.license,acceptedAt:new Date().toISOString()}));const archive=path.join(this.root,'downloads',r.archive);if(!findServer(path.join(this.root,'runtimes',RELEASE,runtimeKey()))){await download(`https://github.com/ggml-org/llama.cpp/releases/download/${RELEASE}/${r.archive}`,archive,r.sha256,p=>onProgress?.({...p,stage:'runtime'}));await extract(archive,path.join(this.root,'runtimes',RELEASE,runtimeKey()));}const modelPath=this.modelPath(selected);if(!fs.existsSync(modelPath))await download(selected.url,modelPath,selected.sha256,p=>onProgress?.({...p,stage:'model',modelId:selected.id}));return this.state();}
 async chat(message,context){if(!this.state().ready)throw new Error('Ask Jerri is not ready. Set up a verified local model first.');const port=await this.startServer();const prompt=`You are Ask Jerri, a private finance explainer. Never invent numbers, never give tax/legal/investment advice, and never mutate data. Use only the deterministic context below. If it is insufficient, say so.
CONTEXT:
${JSON.stringify(context)}
USER:
${message}`;const response=await fetch(`http://127.0.0.1:${port}/v1/chat/completions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:'Answer briefly and clearly.'},{role:'user',content:prompt}],temperature:0.1,max_tokens:500})});if(!response.ok)throw new Error(`Local AI returned HTTP ${response.status}.`);const body=await response.json();return body.choices?.[0]?.message?.content||'The local model returned no answer.';}
 async startServer(){if(this.server&&this.serverPort)return this.serverPort;const r=this.state().runtime,port=39000+Math.floor(Math.random()*1000);this.server=spawn(r.serverPath,['-m',this.modelPath(),'--host','127.0.0.1','--port',String(port),'--no-webui'],{cwd:path.dirname(r.serverPath),stdio:'ignore'});this.server.on('exit',()=>{this.server=null;this.serverPort=null});for(let i=0;i<60;i++){try{const response=await fetch(`http://127.0.0.1:${port}/health`);if(response.ok){this.serverPort=port;return port}}catch{}await new Promise(resolve=>setTimeout(resolve,250))}throw new Error('The local AI runtime did not become ready.');}
 close(){this.server?.kill();this.server=null;this.serverPort=null;}
}
export {MODEL,MODELS,RUNTIMES,runtimeKey};