import 'dotenv/config';
import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from './config.mjs';
import { openDatabase, id, audit } from './db.mjs';
import { stageImport, getImport, commitImport, revertImport, clearImportedData, resetWorkspace, createManualTransaction, deleteManualTransaction, bootstrap, dashboard, updateTransaction, toTransaction, toImport, toRule, toAllocation, toHolding } from './service.mjs';
import { createBackupBundle, decodeAndValidateBackup, replaceDatabaseSafely } from './backup.mjs';

let db=openDatabase(); const app=express(); app.disable('x-powered-by'); app.use(express.json({limit:'1mb'}));
app.use((req,res,next)=>{ res.setHeader('Cache-Control','no-store'); next(); });
if (config.authUser || config.authPassword) app.use((req,res,next)=>{ if (req.path === '/api/health') return next(); const header=req.headers.authorization ?? ''; const expected=Buffer.from(`${config.authUser}:${config.authPassword}`).toString('base64'); if (header !== `Basic ${expected}`) { res.setHeader('WWW-Authenticate','Basic realm=\"Jerri Finance\"'); return res.status(401).json({error:'Authentication required'}); } return next(); });
const sendError=(res,error)=>res.status(error.status ?? 500).json({error:error.message ?? 'Unexpected server error', importId:error.importId});

app.get('/api/health', (_req,res)=>res.json({status:'ok', mode:config.publicMode ? 'public-protected' : 'local-only', database:'sqlite'}));
app.get('/api/version', (_req,res)=>res.json({commit:config.commit, environment:config.environment}));
app.get('/api/bootstrap', (_req,res)=>res.json(bootstrap(db)));
app.patch('/api/accounts/:id',(req,res)=>{try{const before=db.prepare('SELECT * FROM accounts WHERE id=?').get(req.params.id);if(!before)throw Object.assign(new Error('Import source not found'),{status:404});const active=Number(Boolean(req.body.active));db.prepare('UPDATE accounts SET active=? WHERE id=?').run(active,req.params.id);const after=db.prepare('SELECT * FROM accounts WHERE id=?').get(req.params.id);audit(db,'account',after.id,active?'enabled':'disabled',before,after);res.json({id:after.id,provider:after.source_type,displayName:after.name,status:after.active?'connected':'disconnected'});}catch(e){sendError(res,e);}});
app.get('/api/dashboard', (req,res)=>res.json(dashboard(db, typeof req.query.month === 'string' ? req.query.month : null)));
app.get('/api/transactions/export.csv', (_req,res)=>{ const rows=db.prepare('SELECT occurred_on,description,source_account_id,amount_minor,kind,is_business,include_in_profit,review_status FROM transactions ORDER BY occurred_on DESC').all(); const csv=['Date,Description,Source,Amount,Type,Scope,Included In Profit,Status',...rows.map(row=>[row.occurred_on,`"${String(row.description).replaceAll('"','""')}"`,row.source_account_id,(row.amount_minor/100).toFixed(2),row.kind,row.review_status==='needs_review'?'unknown':row.is_business?'business':'personal',row.include_in_profit?'true':'false',row.review_status].join(','))].join(String.fromCharCode(10)); res.type('text/csv').send(csv); });
app.get('/api/transactions', (req,res)=> { let sql='SELECT * FROM transactions'; if(req.query.review==='true'){sql+=' WHERE review_status=\'needs_review\'';} sql+=' ORDER BY occurred_on DESC, created_at DESC'; res.json(db.prepare(sql).all().map(toTransaction)); });
app.patch('/api/transactions/:id',(req,res)=>{ try{res.json(updateTransaction(db,req.params.id,req.body));}catch(e){sendError(res,e);} });
app.post('/api/transactions/:id/review',(req,res)=>{try{if(!['business','personal'].includes(req.body.scope)||!req.body.categoryId||typeof req.body.includedInProfit!=='boolean')throw Object.assign(new Error('Review requires an explicit scope, category, and profit-inclusion decision.'),{status:400});res.json(updateTransaction(db,req.params.id,{...req.body,reviewStatus:'reviewed'}));}catch(e){sendError(res,e);}});
app.post('/api/transactions', (req,res)=>{try{res.status(201).json(createManualTransaction(db,req.body));}catch(e){sendError(res,e);}});
app.delete('/api/transactions/:id', (req,res)=>{try{deleteManualTransaction(db,req.params.id);res.status(204).end();}catch(e){sendError(res,e);}});
app.post('/api/transactions/bulk-categorize',(req,res)=>{try{const {transactionIds=[],categoryId,scope='personal',includedInProfit=false}=req.body; const results=transactionIds.map(transactionId=>updateTransaction(db,transactionId,{categoryId,scope,includedInProfit:scope==='business' && Boolean(includedInProfit),reviewStatus:'reviewed'})); res.json(results);}catch(e){sendError(res,e);}});
app.get('/api/imports',(req,res)=>res.json(db.prepare('SELECT * FROM import_jobs ORDER BY created_at DESC').all().map(toImport)));
app.get('/api/imports/:id',(req,res)=>{const result=getImport(db,req.params.id); result ? res.json(result) : res.status(404).json({error:'Import not found'});});
app.post('/api/imports/:id/commit',(req,res)=>{try{res.json(commitImport(db,req.params.id));}catch(e){sendError(res,e);}});
app.post('/api/imports/:id/revert',(req,res)=>{try{res.json(revertImport(db,req.params.id));}catch(e){sendError(res,e);}});
app.post('/api/data/clear-imported',(req,res)=>{try{res.json(clearImportedData(db));}catch(e){sendError(res,e);}});
app.post('/api/workspace/reset',(req,res)=>{try{res.json(resetWorkspace(db));}catch(e){sendError(res,e);}});
app.get('/api/category-rules',(_req,res)=>res.json(db.prepare('SELECT * FROM category_rules ORDER BY priority').all().map(toRule)));
app.post('/api/category-rules',(req,res)=>{try{const now=new Date().toISOString(); const condition=req.body.conditions?.[0]; const action=req.body.action??req.body; const isBusiness=(action.scope??'personal')==='business'; const rule={id:id('rule'),pattern:String(condition?.value??req.body.pattern??'').toLowerCase().trim(),categoryId:action.categoryId,isBusiness:Number(isBusiness),includeInProfit:Number(isBusiness && Boolean(action.includedInProfit??req.body.includeInProfit)),priority:Number(req.body.priority??100)}; if(!rule.pattern||!rule.categoryId) throw Object.assign(new Error('A description condition and category are required'),{status:400}); db.prepare('INSERT INTO category_rules VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(rule.id,rule.pattern,rule.categoryId,rule.isBusiness,rule.includeInProfit,rule.priority,now,now); audit(db,'category_rule',rule.id,'created',null,rule);res.status(201).json(toRule(db.prepare('SELECT * FROM category_rules WHERE id=?').get(rule.id)));}catch(e){sendError(res,e);}});
app.patch('/api/category-rules/:id',(req,res)=>{try{const before=db.prepare('SELECT * FROM category_rules WHERE id=?').get(req.params.id);if(!before)throw Object.assign(new Error('Rule not found'),{status:404});const condition=req.body.conditions?.[0];const action=req.body.action??req.body;const after={...before,pattern:condition?.value??req.body.pattern??before.pattern,category_id:action.categoryId??req.body.categoryId??before.category_id,is_business:action.scope===undefined?(req.body.isBusiness===undefined?before.is_business:Number(Boolean(req.body.isBusiness))):Number(action.scope==='business'),include_in_profit:((action.scope===undefined ? (req.body.isBusiness===undefined ? before.is_business : Number(Boolean(req.body.isBusiness))) : Number(action.scope==='business')) ? (action.includedInProfit===undefined ? (req.body.includeInProfit===undefined ? before.include_in_profit : Number(Boolean(req.body.includeInProfit))) : Number(Boolean(action.includedInProfit))) : 0),priority:req.body.priority??before.priority,updated_at:new Date().toISOString()};db.prepare('UPDATE category_rules SET pattern=?,category_id=?,is_business=?,include_in_profit=?,priority=?,updated_at=? WHERE id=?').run(after.pattern,after.category_id,after.is_business,after.include_in_profit,after.priority,after.updated_at,req.params.id);audit(db,'category_rule',req.params.id,'updated',before,after);res.json(toRule(after));}catch(e){sendError(res,e);}});
app.delete('/api/category-rules/:id',(req,res)=>{const before=db.prepare('SELECT * FROM category_rules WHERE id=?').get(req.params.id);if(!before)return res.status(404).json({error:'Rule not found'});db.prepare('DELETE FROM category_rules WHERE id=?').run(req.params.id);audit(db,'category_rule',req.params.id,'deleted',before,null);res.status(204).end();});
app.post('/api/category-rules/apply',(_req,res)=>{try{const rules=db.prepare('SELECT * FROM category_rules ORDER BY priority').all();const changed=[];db.exec('BEGIN IMMEDIATE');for(const rule of rules){const matches=db.prepare("SELECT * FROM transactions WHERE lower(description) LIKE '%' || ? || '%'").all(rule.pattern);for(const before of matches){db.prepare("UPDATE transactions SET category_id=?,is_business=?,include_in_profit=?,review_status='auto_categorized',updated_at=? WHERE id=?").run(rule.category_id,rule.is_business,rule.is_business ? rule.include_in_profit : 0,new Date().toISOString(),before.id);const after=db.prepare('SELECT * FROM transactions WHERE id=?').get(before.id);audit(db,'transaction',before.id,'rule_applied',before,after);changed.push(toTransaction(after));}}db.exec('COMMIT');res.json({updated:changed});}catch(e){try{db.exec('ROLLBACK');}catch{}sendError(res,e);}});
app.get('/api/allocation-rules',(_req,res)=>res.json(db.prepare('SELECT * FROM allocation_rules ORDER BY sort_order').all().map(toAllocation)));
app.patch('/api/allocation-rules',(req,res)=>{try{const rules=req.body.rules;const stored=db.prepare('SELECT id FROM allocation_rules ORDER BY sort_order').all();const incomingIds=new Set(Array.isArray(rules)?rules.map(rule=>rule.id):[]);const validShape=Array.isArray(rules)&&rules.length===stored.length&&stored.every(rule=>incomingIds.has(rule.id));const validValues=validShape&&rules.every(rule=>Number.isInteger(Number(rule.percentageBps))&&Number(rule.percentageBps)>=0&&Number(rule.percentageBps)<=10000);if(!validValues||rules.reduce((n,r)=>n+Number(r.percentageBps),0)!==10000)throw Object.assign(new Error('Submit every allocation rule with whole basis points totalling exactly 100%.'),{status:400});db.exec('BEGIN IMMEDIATE');for(const rule of rules)db.prepare('UPDATE allocation_rules SET percentage_bps=?, updated_at=? WHERE id=?').run(Number(rule.percentageBps),new Date().toISOString(),rule.id);db.exec('COMMIT');audit(db,'allocation_rules','all','updated',null,rules);res.json(db.prepare('SELECT * FROM allocation_rules ORDER BY sort_order').all().map(toAllocation));}catch(e){try{db.exec('ROLLBACK');}catch{}sendError(res,e);}});
const today=()=>new Date().toISOString().slice(0,10);
app.post('/api/assets',(req,res)=>{try{const row={id:id('asset'),name:String(req.body.name??'').trim(),amountMinor:Number(req.body.valueMinor),asOf:req.body.asOf??today(),category:String(req.body.category??'savings')};if(!row.name||!Number.isSafeInteger(row.amountMinor))throw Object.assign(new Error('name and integer valueMinor are required'),{status:400});db.prepare('INSERT INTO assets (id,name,amount_minor,as_of_date,category,created_at) VALUES (?, ?, ?, ?, ?, ?)').run(row.id,row.name,row.amountMinor,row.asOf,row.category,new Date().toISOString());audit(db,'asset',row.id,'created',null,row);res.status(201).json({id:row.id,name:row.name,valueMinor:row.amountMinor,asOf:row.asOf,category:req.body.category??'savings',currency:'AUD'});}catch(e){sendError(res,e);}});
app.patch('/api/assets/:id',(req,res)=>{try{const before=db.prepare('SELECT * FROM assets WHERE id=?').get(req.params.id);if(!before)throw Object.assign(new Error('Asset not found'),{status:404});const name=req.body.name===undefined?before.name:String(req.body.name).trim();const amountMinor=req.body.valueMinor===undefined?before.amount_minor:Number(req.body.valueMinor);const asOf=req.body.asOf??before.as_of_date;if(!name||!Number.isSafeInteger(amountMinor)||!/^\d{4}-\d{2}-\d{2}$/.test(asOf))throw Object.assign(new Error('name, integer valueMinor and valid asOf are required'),{status:400});db.prepare('UPDATE assets SET name=?,amount_minor=?,as_of_date=? WHERE id=?').run(name,amountMinor,asOf,req.params.id);const category=req.body.category===undefined?before.category:String(req.body.category);db.prepare('UPDATE assets SET category=? WHERE id=?').run(category,req.params.id);const after=db.prepare('SELECT * FROM assets WHERE id=?').get(req.params.id);audit(db,'asset',req.params.id,'updated',before,after);res.json({id:after.id,name:after.name,valueMinor:after.amount_minor,asOf:after.as_of_date,category:after.category,currency:'AUD'});}catch(e){sendError(res,e);}});
app.delete('/api/assets/:id',(req,res)=>{const row=db.prepare('SELECT * FROM assets WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({error:'Asset not found'});db.prepare('DELETE FROM assets WHERE id=?').run(req.params.id);audit(db,'asset',row.id,'deleted',row,null);res.status(204).end();});
app.post('/api/liabilities',(req,res)=>{try{const row={id:id('liability'),name:String(req.body.name??'').trim(),amountMinor:Number(req.body.balanceMinor),asOf:req.body.asOf??today(),category:String(req.body.category??'credit_card')};if(!row.name||!Number.isSafeInteger(row.amountMinor))throw Object.assign(new Error('name and integer balanceMinor are required'),{status:400});db.prepare('INSERT INTO liabilities (id,name,amount_minor,as_of_date,category,created_at) VALUES (?, ?, ?, ?, ?, ?)').run(row.id,row.name,row.amountMinor,row.asOf,row.category,new Date().toISOString());audit(db,'liability',row.id,'created',null,row);res.status(201).json({...row,balanceMinor:row.amountMinor,category:req.body.category??'credit_card',currency:'AUD'});}catch(e){sendError(res,e);}});
app.patch('/api/liabilities/:id',(req,res)=>{try{const before=db.prepare('SELECT * FROM liabilities WHERE id=?').get(req.params.id);if(!before)throw Object.assign(new Error('Liability not found'),{status:404});const name=req.body.name===undefined?before.name:String(req.body.name).trim();const balanceMinor=req.body.balanceMinor===undefined?before.amount_minor:Number(req.body.balanceMinor);const asOf=req.body.asOf??before.as_of_date;if(!name||!Number.isSafeInteger(balanceMinor)||!/^\d{4}-\d{2}-\d{2}$/.test(asOf))throw Object.assign(new Error('name, integer balanceMinor and valid asOf are required'),{status:400});db.prepare('UPDATE liabilities SET name=?,amount_minor=?,as_of_date=? WHERE id=?').run(name,balanceMinor,asOf,req.params.id);const category=req.body.category===undefined?before.category:String(req.body.category);db.prepare('UPDATE liabilities SET category=? WHERE id=?').run(category,req.params.id);const after=db.prepare('SELECT * FROM liabilities WHERE id=?').get(req.params.id);audit(db,'liability',req.params.id,'updated',before,after);res.json({id:after.id,name:after.name,balanceMinor:after.amount_minor,asOf:after.as_of_date,category:after.category,currency:'AUD'});}catch(e){sendError(res,e);}});
app.delete('/api/liabilities/:id',(req,res)=>{const row=db.prepare('SELECT * FROM liabilities WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({error:'Liability not found'});db.prepare('DELETE FROM liabilities WHERE id=?').run(req.params.id);audit(db,'liability',row.id,'deleted',row,null);res.status(204).end();});
app.get('/api/holdings',(_req,res)=>res.json(db.prepare('SELECT * FROM holdings ORDER BY as_of_date DESC, created_at DESC').all().map(toHolding)));
app.post('/api/holdings',(req,res)=>{try{const row={id:id('holding'),name:String(req.body.name??'').trim(),category:String(req.body.category??'etf'),units:req.body.units === '' || req.body.units === undefined ? null : Number(req.body.units),valueMinor:Number(req.body.currentValueMinor),monthlyContributionMinor:Number(req.body.monthlyContributionMinor??0),returnMtdMinor:Number(req.body.returnMtdMinor??0),annualReturnMinor:Number(req.body.annualReturnMinor??0),asOf:req.body.asOf??today(),createdAt:new Date().toISOString()};if(!row.name||!Number.isSafeInteger(row.valueMinor)||![row.monthlyContributionMinor,row.returnMtdMinor,row.annualReturnMinor].every(Number.isSafeInteger)||!(row.units===null||Number.isFinite(row.units)))throw Object.assign(new Error('A name and whole-number minor amounts are required.'),{status:400});db.prepare('INSERT INTO holdings (id,name,units,value_minor,as_of_date,created_at,category,monthly_contribution_minor,return_mtd_minor,annual_return_minor,updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(row.id,row.name,row.units,row.valueMinor,row.asOf,row.createdAt,row.category,row.monthlyContributionMinor,row.returnMtdMinor,row.annualReturnMinor,row.createdAt);const saved=db.prepare('SELECT * FROM holdings WHERE id=?').get(row.id);audit(db,'holding',row.id,'created',null,saved);res.status(201).json(toHolding(saved));}catch(e){sendError(res,e);}});
app.patch('/api/holdings/:id',(req,res)=>{try{const before=db.prepare('SELECT * FROM holdings WHERE id=?').get(req.params.id);if(!before)throw Object.assign(new Error('Holding not found'),{status:404});const changes={name:req.body.name===undefined?before.name:String(req.body.name).trim(),category:req.body.category??before.category,units:req.body.units===undefined?before.units:(req.body.units===''?null:Number(req.body.units)),valueMinor:req.body.currentValueMinor===undefined?before.value_minor:Number(req.body.currentValueMinor),monthlyContributionMinor:req.body.monthlyContributionMinor===undefined?before.monthly_contribution_minor:Number(req.body.monthlyContributionMinor),returnMtdMinor:req.body.returnMtdMinor===undefined?before.return_mtd_minor:Number(req.body.returnMtdMinor),annualReturnMinor:req.body.annualReturnMinor===undefined?before.annual_return_minor:Number(req.body.annualReturnMinor),asOf:req.body.asOf??before.as_of_date};if(!changes.name||!Number.isSafeInteger(changes.valueMinor)||![changes.monthlyContributionMinor,changes.returnMtdMinor,changes.annualReturnMinor].every(Number.isSafeInteger)||!(changes.units===null||Number.isFinite(changes.units)))throw Object.assign(new Error('Invalid holding values.'),{status:400});const timestamp=new Date().toISOString();db.prepare('UPDATE holdings SET name=?,category=?,units=?,value_minor=?,monthly_contribution_minor=?,return_mtd_minor=?,annual_return_minor=?,as_of_date=?,updated_at=? WHERE id=?').run(changes.name,changes.category,changes.units,changes.valueMinor,changes.monthlyContributionMinor,changes.returnMtdMinor,changes.annualReturnMinor,changes.asOf,timestamp,req.params.id);const after=db.prepare('SELECT * FROM holdings WHERE id=?').get(req.params.id);audit(db,'holding',req.params.id,'updated',before,after);res.json(toHolding(after));}catch(e){sendError(res,e);}});
app.delete('/api/holdings/:id',(req,res)=>{const row=db.prepare('SELECT * FROM holdings WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({error:'Holding not found'});db.prepare('DELETE FROM holdings WHERE id=?').run(req.params.id);audit(db,'holding',row.id,'deleted',row,null);res.status(204).end();});
app.patch('/api/profile',(req,res)=>{try{const before=db.prepare('SELECT * FROM profiles WHERE id=\'owner\'').get();let previous={};try{previous=JSON.parse(db.prepare("SELECT value FROM settings WHERE key='profile'").get()?.value??'{}');}catch{}const after={id:'owner',name:req.body.name??previous.name??'Jerri Zerafa Finance',type:req.body.type??previous.type??'Sole trader',abn:req.body.abn??previous.abn??'',ownerName:String(req.body.ownerName??previous.ownerName??before.display_name),email:req.body.email??previous.email??'',currency:req.body.currency??previous.currency??before.currency,financialYearStartMonth:req.body.financialYearStartMonth??previous.financialYearStartMonth??7};db.prepare('UPDATE profiles SET display_name=?,currency=? WHERE id=\'owner\'').run(after.ownerName,after.currency);db.prepare('INSERT INTO settings VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').run('profile',JSON.stringify(after),new Date().toISOString());audit(db,'profile','owner','updated',previous,after);res.json(after);}catch(e){sendError(res,e);}});
app.patch('/api/settings',(req,res)=>{try{const {section,payload}=req.body;if(!['importPreferences','notifications','security'].includes(section))throw Object.assign(new Error('Unknown settings section'),{status:400});const base=bootstrap(db).settings;const next={...base,[section]:{...base[section],...payload}};db.prepare('INSERT INTO settings VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').run(section,JSON.stringify(next[section]),new Date().toISOString());audit(db,'settings',section,'updated',base[section],next[section]);res.json(next);}catch(e){sendError(res,e);}});

app.get('/api/backups/status',(_req,res)=>res.json({localOnly:config.host === '127.0.0.1', backupFormat:'jerri-finance-backup', version:1, database:'SQLite'}));
app.get('/api/backups/export',(_req,res)=>{try{const backup=createBackupBundle(db); audit(db,'backup','local','exported',null,backup.manifest); res.setHeader('Content-Type','application/json');res.setHeader('Content-Disposition',`attachment; filename="jerri-finance-backup-${backup.manifest.createdAt.slice(0,10)}.json"`);res.setHeader('Content-Length',backup.encoded.length);res.send(backup.encoded);}catch(e){sendError(res,e);}});

const distDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','dist');
if(fs.existsSync(distDir)) { app.use(express.static(distDir,{index:false})); app.get('*',(req,res,next)=>req.path.startsWith('/api/')?next():res.sendFile(path.join(distDir,'index.html'))); }

function multipartParts(req) { const type=req.headers['content-type']??''; const boundary=type.match(/boundary=(?:"([^"]+)"|([^;]+))/)?.slice(1).find(Boolean); if(!boundary) throw Object.assign(new Error('multipart/form-data with a boundary is required'),{status:400}); const chunks=[]; const marker=Buffer.from(`--${boundary}`); let start=0; while(true){const hit=req.body.indexOf(marker,start);if(hit<0)break;const next=req.body.indexOf(marker,hit+marker.length);if(next<0)break;const part=req.body.subarray(hit+marker.length+2,next-2);const headerEnd=part.indexOf(Buffer.from('\r\n\r\n'));if(headerEnd>0){const headers=part.subarray(0,headerEnd).toString();const name=headers.match(/name="([^"]+)"/)?.[1];const filename=headers.match(/filename="([^"]*)"/)?.[1];const data=part.subarray(headerEnd+4);chunks.push({name,filename,data});}start=next;} return chunks; }
function parseMultipart(req) { const chunks=multipartParts(req); const source=chunks.find(c=>c.name==='sourceAccountId' || c.name==='source')?.data.toString() || 'auto';const file=chunks.find(c=>c.name==='file');if(!file?.filename)throw Object.assign(new Error('A file is required.'),{status:400});return {sourceAccountId:source,fileName:file.filename,buffer:file.data}; }
app.post('/api/imports',express.raw({type:'multipart/form-data',limit:config.uploadLimitBytes}),async (req,res)=>{try{const staged=await stageImport(db,parseMultipart(req)); res.status(201).json(staged);}catch(e){sendError(res,e);}});
app.post('/api/backups/restore',express.raw({type:'multipart/form-data',limit:'50mb'}),(req,res)=>{try{const file=multipartParts(req).find(part=>part.name==='file');if(!file?.filename)throw Object.assign(new Error('Select a Jerri Finance backup file first.'),{status:400});const validated=decodeAndValidateBackup(file.data);const oldDb=db;try{db=replaceDatabaseSafely(oldDb,validated.database,openDatabase);}catch(error){try{db=openDatabase();}catch{}throw error;}audit(db,'backup','local','restored',null,validated.manifest);res.json({restored:true,manifest:validated.manifest});}catch(e){sendError(res,e);}});
app.use((error,_req,res,_next)=>sendError(res,error));
app.listen(config.port,config.host,()=>console.log(`Jerri Finance Portal ${config.publicMode ? 'protected' : 'local'} API: http://${config.host}:${config.port}`));
