import React, { useState } from 'react';
import { Pencil, Plus, Trash2, X } from 'lucide-react';
import { useFinance } from '../context/FinanceContext';
import { HeroBanner } from '../components/common/HeroBanner';
import { DonutChart } from '../components/common/Charts';
import { formatMoney } from '../domain/formatters';
import { selectPortfolioValue, selectTotalMonthlyContributions, selectMtdPassiveIncome } from '../domain/selectors';
import type { InvestmentHolding } from '../types';

const categories = ['etf', 'shares', 'super', 'cash', 'emergency', 'growth', 'passive_income'];
const toMinor = (value: string) => Math.round(Number(value || 0) * 100);
const moneyInput = (value?: number) => ((value ?? 0) / 100).toFixed(2);
type Draft = Omit<InvestmentHolding, 'id'>;
const blank = (): Draft => ({ name: '', category: 'etf', currentValueMinor: 0, monthlyContributionMinor: 0, returnMtdMinor: 0, annualReturnMinor: 0, asOf: new Date().toISOString().slice(0, 10) });

export const InvestmentsPage: React.FC = () => {
  const { holdings, addHolding, updateHolding, deleteHolding } = useFinance();
  const [draft, setDraft] = useState<Draft>(blank());
  const [editingId, setEditingId] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const portfolioValue = selectPortfolioValue(holdings);
  const monthlyContrib = selectTotalMonthlyContributions(holdings);
  const passiveIncome = selectMtdPassiveIncome(holdings);
  const donut = holdings.map((h, idx) => ({ label: h.name, value: h.currentValueMinor, color: ['#1547F5','#16A35A','#7338F5','#12AFC8','#F59E0B'][idx % 5] }));
  const begin = (holding?: InvestmentHolding) => { setError(null); setEditingId(holding?.id ?? null); setDraft(holding ? { ...holding } : blank()); setOpen(true); };
  const save = async () => { if (!draft.name.trim()) return setError('Enter a holding name.'); setSaving(true); setError(null); try { if (editingId) await updateHolding(editingId, draft); else await addHolding(draft); setOpen(false); } catch { setError('Could not save the holding. Check the values and try again.'); } finally { setSaving(false); } };
  const field = (key: keyof Draft, label: string, type = 'text') => <label className="block text-[11px] font-semibold text-slate-500 uppercase">{label}<input type={type} value={type === 'number' ? moneyInput(draft[key] as number) : String(draft[key] ?? '')} step="0.01" onChange={e => setDraft(d => ({ ...d, [key]: type === 'number' ? toMinor(e.target.value) : e.target.value }))} className="w-full mt-1 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-[13px] text-slate-900" /></label>;
  return <div className="space-y-6">
    <HeroBanner title="Investments & Wealth" subtitle="Positions and values stored only on this computer."><div className="rounded-xl border border-white/15 bg-white/10 p-4 text-white"><div className="text-[10px] uppercase text-blue-100">Portfolio value</div><div className="text-[22px] font-extrabold">{formatMoney(portfolioValue)}</div></div></HeroBanner>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Metric label="Portfolio market value" value={formatMoney(portfolioValue)} /><Metric label="Monthly contribution" value={formatMoney(monthlyContrib)} /><Metric label="Income recorded this month" value={formatMoney(passiveIncome)} /></div>
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-5"><div className="lg:col-span-2 rounded-[14px] border border-slate-200 bg-white p-5"><h3 className="mb-3 text-[15px] font-semibold">Asset allocation</h3><DonutChart data={donut} centerLabel="Investments" centerValue={formatMoney(portfolioValue)} /></div><div className="lg:col-span-3 rounded-[14px] border border-slate-200 bg-white p-5"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><div><h3 className="text-[15px] font-semibold">Holdings & position details</h3><p className="text-[11px] text-slate-400">Add, edit or remove each tracked investment.</p></div><button onClick={() => begin()} className="flex items-center gap-1 rounded-lg bg-slate-900 px-3 py-2 text-[12px] font-semibold text-white"><Plus size={14}/> Add holding</button></div><div className="overflow-x-auto"><table className="w-full text-left text-[12px]"><thead className="text-[10px] uppercase text-slate-400"><tr><th className="py-3">Holding</th><th>Category</th><th>Value</th><th>Monthly</th><th>As at</th><th></th></tr></thead><tbody>{holdings.map(h => <tr key={h.id} className="border-t border-slate-100"><td className="py-3 font-semibold">{h.name}</td><td className="capitalize text-slate-500">{h.category.replace('_',' ')}</td><td className="font-semibold">{formatMoney(h.currentValueMinor)}</td><td>{h.monthlyContributionMinor ? formatMoney(h.monthlyContributionMinor) : '—'}</td><td className="text-slate-500">{h.asOf}</td><td className="whitespace-nowrap"><button aria-label={`Edit ${h.name}`} onClick={() => begin(h)} className="p-1 text-slate-500"><Pencil size={14}/></button><button aria-label={`Delete ${h.name}`} onClick={() => { if (window.confirm(`Remove ${h.name}?`)) void deleteHolding(h.id); }} className="p-1 text-rose-600"><Trash2 size={14}/></button></td></tr>)}{holdings.length===0 && <tr><td colSpan={6} className="py-8 text-center text-slate-400">No holdings recorded yet.</td></tr>}</tbody></table></div></div></div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="mb-4 flex justify-between border-b pb-3"><h3 className="font-bold">{editingId ? 'Edit holding' : 'Add investment holding'}</h3><button onClick={() => setOpen(false)}><X size={20}/></button></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{field('name','Holding name')}<label className="block text-[11px] font-semibold uppercase text-slate-500">Category<select value={draft.category} onChange={e => setDraft(d => ({...d,category:e.target.value}))} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-[13px]">{categories.map(c => <option key={c} value={c}>{c.replace('_',' ')}</option>)}</select></label>{field('currentValueMinor','Current value (AUD)','number')}{field('monthlyContributionMinor','Monthly contribution (AUD)','number')}{field('returnMtdMinor','Income / return this month (AUD)','number')}{field('annualReturnMinor','Annual return recorded (AUD)','number')}<label className="block text-[11px] font-semibold uppercase text-slate-500">As at<input type="date" value={draft.asOf} onChange={e => setDraft(d => ({...d,asOf:e.target.value}))} className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-[13px]"/></label></div>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={() => setOpen(false)} className="rounded-lg px-4 py-2 text-sm text-slate-600">Cancel</button><button disabled={saving} onClick={() => void save()} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{saving ? 'Saving…' : 'Save holding'}</button></div></div></div>}
  </div>;
};
const Metric = ({label,value}:{label:string;value:string}) => <div className="rounded-[14px] border border-slate-200 bg-white p-5"><div className="text-[12px] text-slate-500">{label}</div><div className="mt-1 text-[22px] font-bold tabular-nums">{value}</div><div className="mt-1 text-[11px] text-slate-400">Current local records</div></div>;
